// ─── Competition Seed Data ─────────────────────────────────────────────────────
// 30 major recurring US ballroom dance competitions.
// Levels: Professional · Amateur · Pro/Am only (Collegiate + Senior added later).
// dateStart / dateEnd: set to 2026 confirmed dates where known; null = TBA.
// Phase 2 will migrate this to a WordPress CPT (dance_competition post type).

import type { Competition } from "@/types/competition";

export const COMPETITIONS: Competition[] = [

  // ── WEST COAST ──────────────────────────────────────────────────────────────

  {
    slug:                "millennium-dancesport",
    name:                "Millennium DanceSport Championship",
    dateStart:           "2026-01-15",
    dateEnd:             "2026-01-18",
    typicalMonth:        1,
    venue:               "LAX Marriott",
    city:                "Los Angeles",
    state:               "California",
    stateAbbr:           "CA",
    citySlug:            "los-angeles",
    region:              "west",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["professional","amateur","pro_am"],
    description:         "The Millennium DanceSport Championship opens the NDCA Premier competitive season each January in Los Angeles. One of the most prestigious West Coast events, it draws top professional and Pro/Am couples from across North America for intense competition across all four major dance styles.",
    website:             "https://millenniumdancesport.com",
    registrationUrl:     "https://millenniumdancesport.com/registration",
    registrationDeadline: "2026-01-05",
    entryFeeMin:         15,
    entryFeeMax:         30,
    isFeatured:          true,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "desert-classic-dancesport",
    name:                "Desert Classic DanceSport Championships",
    dateStart:           "2026-02-19",
    dateEnd:             "2026-02-22",
    typicalMonth:        2,
    venue:               "Hilton Palm Springs",
    city:                "Palm Springs",
    state:               "California",
    stateAbbr:           "CA",
    citySlug:            "los-angeles",
    region:              "west",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["professional","amateur","pro_am"],
    description:         "The Desert Classic DanceSport Championships is one of the most beloved winter competitions on the NDCA Premier circuit. Held in sunny Palm Springs, it attracts world-class professionals alongside hundreds of Pro/Am and Amateur couples in a warm, social atmosphere unlike any other event.",
    website:             "https://www.desertclassicdancesport.com",
    registrationUrl:     "https://www.desertclassicdancesport.com/registration",
    registrationDeadline: "2026-02-01",
    entryFeeMin:         18,
    entryFeeMax:         35,
    isFeatured:          true,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "emerald-ball-dancesport",
    name:                "Emerald Ball DanceSport Championships",
    dateStart:           "2026-05-07",
    dateEnd:             "2026-05-10",
    typicalMonth:        5,
    venue:               "Los Angeles Airport Marriott",
    city:                "Los Angeles",
    state:               "California",
    stateAbbr:           "CA",
    citySlug:            "los-angeles",
    region:              "west",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm","swing"],
    levels:              ["professional","amateur","pro_am"],
    description:         "The Emerald Ball is one of the most celebrated competitions on the West Coast, running each May in Los Angeles. With a rich history spanning decades, it offers a full slate of Professional, Amateur, and Pro/Am divisions across all major styles, drawing competitors and spectators from around the world.",
    website:             "https://www.emeraldball.com",
    registrationUrl:     "https://www.emeraldball.com/register",
    registrationDeadline: "2026-04-15",
    entryFeeMin:         18,
    entryFeeMax:         38,
    isFeatured:          true,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "pacific-coast-classic-dancesport",
    name:                "Pacific Coast Classic DanceSport",
    dateStart:           "2026-09-10",
    dateEnd:             "2026-09-13",
    typicalMonth:        9,
    venue:               "Sheraton Gateway Los Angeles",
    city:                "Los Angeles",
    state:               "California",
    stateAbbr:           "CA",
    citySlug:            "los-angeles",
    region:              "west",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["professional","amateur","pro_am"],
    description:         "The Pacific Coast Classic is a cornerstone fall competition on the NDCA Premier circuit, held each September in Los Angeles. Known for its top-tier Professional divisions and highly competitive Pro/Am field, it draws studio owners and coaches from across California and the Pacific Northwest.",
    website:             "https://www.pacificcoastclassicdancesport.com",
    registrationDeadline: null,
    entryFeeMin:         16,
    entryFeeMax:         32,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "california-star-ball",
    name:                "California Star Ball",
    dateStart:           "2026-10-01",
    dateEnd:             "2026-10-04",
    typicalMonth:        10,
    venue:               "Ontario Airport Marriott",
    city:                "Los Angeles",
    state:               "California",
    stateAbbr:           "CA",
    citySlug:            "los-angeles",
    region:              "west",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["professional","amateur","pro_am"],
    description:         "The California Star Ball is a premier NDCA national ranking event held each fall in the greater Los Angeles area. As a key stop on the Best of the Best DanceSport Series leading to Ohio Star Ball, it carries significant ranking points and attracts a highly competitive Pro/Am and Professional field.",
    website:             "https://www.californiastarball.com",
    registrationDeadline: null,
    entryFeeMin:         18,
    entryFeeMax:         36,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "embassy-ball-dancesport",
    name:                "Embassy Ball DanceSport Championships",
    dateStart:           "2026-11-05",
    dateEnd:             "2026-11-08",
    typicalMonth:        11,
    venue:               "Irvine Marriott",
    city:                "Irvine",
    state:               "California",
    stateAbbr:           "CA",
    citySlug:            "los-angeles",
    region:              "west",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["professional","amateur","pro_am"],
    description:         "The Embassy Ball DanceSport Championships in Irvine, CA is one of the most prestigious end-of-season competitions in North America. Held each November, it draws international Professional couples and a deep Pro/Am field, making it a must-attend event for serious competitors and spectators alike.",
    website:             "https://www.embassyball.com",
    registrationDeadline: null,
    entryFeeMin:         20,
    entryFeeMax:         40,
    isFeatured:          true,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "san-francisco-open-dancesport",
    name:                "San Francisco Open DanceSport",
    dateStart:           null,
    dateEnd:             null,
    typicalMonth:        10,
    venue:               "San Francisco Marriott Marquis",
    city:                "San Francisco",
    state:               "California",
    stateAbbr:           "CA",
    citySlug:            "los-angeles",
    region:              "west",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["amateur","pro_am"],
    description:         "The San Francisco Open DanceSport is a top regional NDCA competition held each fall, drawing amateur and Pro/Am competitors from throughout Northern California, Oregon, and Nevada. Set in the heart of San Francisco, it offers a sophisticated competition environment with strong participation across all four major styles.",
    website:             "https://www.sfopenballroom.com",
    registrationDeadline: null,
    entryFeeMin:         15,
    entryFeeMax:         28,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "seattle-star-ball",
    name:                "Seattle Star Ball",
    dateStart:           null,
    dateEnd:             null,
    typicalMonth:        4,
    venue:               "Seattle Airport Marriott",
    city:                "Seattle",
    state:               "Washington",
    stateAbbr:           "WA",
    citySlug:            "seattle",
    region:              "west",
    organization:        "Independent",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["amateur","pro_am"],
    description:         "The Seattle Star Ball is the Pacific Northwest's premier ballroom dance competition, drawing competitors from Washington, Oregon, British Columbia, and beyond. Known for its welcoming atmosphere and well-organized Pro/Am and Amateur divisions, it's a favorite annual event for dancers throughout the region.",
    website:             "https://www.seattlestarball.com",
    registrationDeadline: null,
    entryFeeMin:         14,
    entryFeeMax:         26,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },

  // ── MOUNTAIN ────────────────────────────────────────────────────────────────

  {
    slug:                "us-national-amateur-dancesport",
    name:                "US National Amateur DanceSport Championships",
    dateStart:           "2026-03-10",
    dateEnd:             "2026-03-14",
    typicalMonth:        3,
    venue:               "Marriott Provo Hotel & Conference Center",
    city:                "Provo",
    state:               "Utah",
    stateAbbr:           "UT",
    citySlug:            "denver",
    region:              "mountain",
    organization:        "USA Dance",
    styles:              ["standard","latin","smooth","rhythm","swing","country"],
    levels:              ["amateur"],
    description:         "Hosted by BYU DanceSport, the US National Amateur DanceSport Championships is the premier sanctioned amateur competition in the United States, drawing elite amateur couples from every state to compete in Standard, Latin, Smooth, Rhythm, Swing, and Country Western. Qualification for the World Amateur Championships routes through this event.",
    website:             "https://usnationals.byudancesport.com",
    registrationUrl:     "https://usnationals.byudancesport.com/register",
    registrationDeadline: "2026-02-15",
    entryFeeMin:         20,
    entryFeeMax:         40,
    isFeatured:          true,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "denver-dancesport",
    name:                "Denver DanceSport Championship",
    dateStart:           null,
    dateEnd:             null,
    typicalMonth:        6,
    venue:               "Hyatt Regency Denver",
    city:                "Denver",
    state:               "Colorado",
    stateAbbr:           "CO",
    citySlug:            "denver",
    region:              "mountain",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["amateur","pro_am"],
    description:         "The Denver DanceSport Championship is the Mountain West's flagship NDCA competition, held each summer at the Hyatt Regency Denver. With a reputation for exceptional organization and a strong Pro/Am field, it attracts couples from Colorado, Wyoming, Utah, and New Mexico who are building their NDCA Premier ranking.",
    website:             "https://www.denverdancesport.com",
    registrationDeadline: null,
    entryFeeMin:         15,
    entryFeeMax:         28,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },

  // ── SOUTHWEST ───────────────────────────────────────────────────────────────

  {
    slug:                "las-vegas-dancesport",
    name:                "Las Vegas DanceSport Championship",
    dateStart:           null,
    dateEnd:             null,
    typicalMonth:        7,
    venue:               "Las Vegas Ballpark Hotel",
    city:                "Las Vegas",
    state:               "Nevada",
    stateAbbr:           "NV",
    citySlug:            "los-angeles",
    region:              "southwest",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["professional","amateur","pro_am"],
    description:         "The Las Vegas DanceSport Championship brings the glitz and energy of Las Vegas to the ballroom dance world each July. An NDCA Premier national ranking event, it attracts Professional and Pro/Am competitors from across the West and Southwest and is known for its spectacular ballroom setting and enthusiastic audience.",
    website:             "https://www.lasvegasdancesport.com",
    registrationDeadline: null,
    entryFeeMin:         16,
    entryFeeMax:         32,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "heritage-classic-dancesport",
    name:                "Heritage Classic DanceSport",
    dateStart:           null,
    dateEnd:             null,
    typicalMonth:        4,
    venue:               "Hilton DFW Lakes Executive Conference Center",
    city:                "Dallas",
    state:               "Texas",
    stateAbbr:           "TX",
    citySlug:            "dallas",
    region:              "southwest",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm","country"],
    levels:              ["professional","amateur","pro_am"],
    description:         "The Heritage Classic DanceSport is Texas's premier NDCA competition, drawing top competitors from across the Southwest and South Central US each spring. Set in the Dallas-Fort Worth metro, it offers Professional, Amateur, and Pro/Am divisions across Standard, Latin, Smooth, Rhythm, and Country Western.",
    website:             "https://www.heritageclassicdancesport.com",
    registrationDeadline: null,
    entryFeeMin:         16,
    entryFeeMax:         30,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "houston-dancesport",
    name:                "Houston DanceSport Championship",
    dateStart:           null,
    dateEnd:             null,
    typicalMonth:        3,
    venue:               "Marriott Houston at the Texas Medical Center",
    city:                "Houston",
    state:               "Texas",
    stateAbbr:           "TX",
    citySlug:            "houston",
    region:              "southwest",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["amateur","pro_am"],
    description:         "The Houston DanceSport Championship is a well-regarded NDCA Premier competition held each spring in the heart of Houston. It draws a strong regional field of Amateur and Pro/Am competitors from Texas, Louisiana, and Oklahoma, with a reputation for smooth organization and a welcoming competition atmosphere.",
    website:             "https://www.houstondancesport.com",
    registrationDeadline: null,
    entryFeeMin:         14,
    entryFeeMax:         26,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },

  // ── MIDWEST ─────────────────────────────────────────────────────────────────

  {
    slug:                "chicago-open-dancesport",
    name:                "Chicago Open DanceSport Championship",
    dateStart:           null,
    dateEnd:             null,
    typicalMonth:        3,
    venue:               "Westin O'Hare",
    city:                "Chicago",
    state:               "Illinois",
    stateAbbr:           "IL",
    citySlug:            "chicago",
    region:              "midwest",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm","swing"],
    levels:              ["professional","amateur","pro_am"],
    description:         "The Chicago Open DanceSport Championship is one of the Midwest's most prestigious NDCA Premier ranking events, held each spring at the Westin O'Hare. Featuring Professional, Amateur, and Pro/Am divisions, it draws competitors from Illinois, Indiana, Michigan, Ohio, and Wisconsin, and is a major stop for couples building their national ranking.",
    website:             "https://www.chicagoopenballroom.com",
    registrationDeadline: null,
    entryFeeMin:         16,
    entryFeeMax:         32,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "indiana-grand-dancesport",
    name:                "Indiana Grand DanceSport",
    dateStart:           null,
    dateEnd:             null,
    typicalMonth:        3,
    venue:               "Indianapolis Marriott East",
    city:                "Indianapolis",
    state:               "Indiana",
    stateAbbr:           "IN",
    citySlug:            "chicago",
    region:              "midwest",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["amateur","pro_am"],
    description:         "The Indiana Grand DanceSport is a respected NDCA Premier competition held each spring in Indianapolis. Known for strong Amateur and Pro/Am participation from across the Midwest, it offers a friendly yet competitive environment and is a popular event for couples working toward national ranking status.",
    website:             "https://www.indianagranddancesport.com",
    registrationDeadline: null,
    entryFeeMin:         13,
    entryFeeMax:         24,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "ohio-star-ball",
    name:                "Ohio Star Ball Championships",
    dateStart:           "2026-11-17",
    dateEnd:             "2026-11-22",
    typicalMonth:        11,
    venue:               "Greater Columbus Convention Center",
    city:                "Columbus",
    state:               "Ohio",
    stateAbbr:           "OH",
    citySlug:            "chicago",
    region:              "midwest",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm","swing","country","multi"],
    levels:              ["professional","amateur","pro_am"],
    description:         "The Ohio Star Ball Championships is the most prestigious ballroom dance competition in North America, serving as the season-ending grand finale of the NDCA Premier national ranking circuit. Held each November in Columbus, Ohio, it crowns the Best of the Best Series champions across all styles and levels, drawing hundreds of the world's top Professional and Pro/Am couples.",
    website:             "https://ohiostarball.com",
    registrationUrl:     "https://ohiostarball.com/osb-registration",
    registrationDeadline: "2026-10-31",
    entryFeeMin:         22,
    entryFeeMax:         45,
    isFeatured:          true,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "minnesota-star-ball",
    name:                "Minnesota Star Ball",
    dateStart:           null,
    dateEnd:             null,
    typicalMonth:        2,
    venue:               "DoubleTree by Hilton Bloomington",
    city:                "Minneapolis",
    state:               "Minnesota",
    stateAbbr:           "MN",
    citySlug:            "chicago",
    region:              "midwest",
    organization:        "Independent",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["amateur","pro_am"],
    description:         "The Minnesota Star Ball is the Twin Cities' premier independent ballroom competition, drawing Amateur and Pro/Am dancers from Minnesota, Wisconsin, Iowa, and the Dakotas each February. Celebrated for its warm community atmosphere and excellent production, it's a standout event in the upper Midwest ballroom calendar.",
    website:             "https://www.minnesotastarball.com",
    registrationDeadline: null,
    entryFeeMin:         13,
    entryFeeMax:         24,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },

  // ── SOUTHEAST ───────────────────────────────────────────────────────────────

  {
    slug:                "usa-dance-nationals",
    name:                "USA Dance National DanceSport Championships",
    dateStart:           "2026-03-27",
    dateEnd:             "2026-03-29",
    typicalMonth:        3,
    venue:               "David L. Lawrence Convention Center",
    city:                "Pittsburgh",
    state:               "Pennsylvania",
    stateAbbr:           "PA",
    citySlug:            "chicago",
    region:              "northeast",
    organization:        "USA Dance",
    styles:              ["standard","latin","smooth","rhythm","swing","country","multi"],
    levels:              ["amateur","pro_am"],
    description:         "The USA Dance National DanceSport Championships is the culminating event of the USA Dance sanctioned competition season. Held in Pittsburgh, it brings together the nation's best Amateur and Pro/Am competitors across all styles and serves as the primary pathway for selection to the Pan American Games and World Championships.",
    website:             "https://usadancenationals.org",
    registrationUrl:     "https://usadancenationals.org/register",
    registrationDeadline: "2026-03-01",
    entryFeeMin:         18,
    entryFeeMax:         36,
    isFeatured:          true,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "united-states-dance-championships",
    name:                "United States Dance Championships",
    dateStart:           null,
    dateEnd:             null,
    typicalMonth:        9,
    venue:               "Rosen Shingle Creek Resort",
    city:                "Orlando",
    state:               "Florida",
    stateAbbr:           "FL",
    citySlug:            "miami",
    region:              "southeast",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm","swing","country","multi"],
    levels:              ["professional","amateur","pro_am"],
    description:         "The United States Dance Championships in Orlando is one of the most comprehensive ballroom competitions in North America, offering divisions in every major style and level across an extended multi-day format. Held each September at the Rosen Shingle Creek Resort, it attracts international professionals and a massive Pro/Am field for a truly world-class event.",
    website:             "https://unitedstatesdancechampionships.com",
    registrationDeadline: null,
    entryFeeMin:         20,
    entryFeeMax:         42,
    isFeatured:          true,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "grand-nationals-dancesport",
    name:                "Grand Nationals DanceSport Championship",
    dateStart:           null,
    dateEnd:             null,
    typicalMonth:        11,
    venue:               "Hyatt Regency Orlando",
    city:                "Orlando",
    state:               "Florida",
    stateAbbr:           "FL",
    citySlug:            "miami",
    region:              "southeast",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["professional","amateur","pro_am"],
    description:         "The Grand Nationals DanceSport Championship is a prestigious NDCA Premier ranking event held each November in Orlando. As one of Florida's top professional competitions, it attracts an elite field of Standard and Latin couples alongside a highly competitive Pro/Am division across American Smooth and Rhythm.",
    website:             "https://www.grandnationalchampionship.com",
    registrationDeadline: null,
    entryFeeMin:         18,
    entryFeeMax:         38,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "hollywood-dancesport",
    name:                "Hollywood DanceSport Championship",
    dateStart:           null,
    dateEnd:             null,
    typicalMonth:        8,
    venue:               "Diplomat Beach Resort",
    city:                "Hollywood",
    state:               "Florida",
    stateAbbr:           "FL",
    citySlug:            "miami",
    region:              "southeast",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["professional","amateur","pro_am"],
    description:         "The Hollywood DanceSport Championship takes place each August at the stunning Diplomat Beach Resort in South Florida, offering spectacular ocean views and a world-class ballroom. An NDCA Premier national ranking event, it draws an international professional field and competitive Pro/Am participants from across Florida and the Caribbean.",
    website:             "https://www.hollywooddancesport.com",
    registrationDeadline: null,
    entryFeeMin:         17,
    entryFeeMax:         34,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "atlanta-dancesport",
    name:                "Atlanta DanceSport Championship",
    dateStart:           null,
    dateEnd:             null,
    typicalMonth:        5,
    venue:               "Atlanta Marriott Buckhead",
    city:                "Atlanta",
    state:               "Georgia",
    stateAbbr:           "GA",
    citySlug:            "atlanta",
    region:              "southeast",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["amateur","pro_am"],
    description:         "The Atlanta DanceSport Championship is the premier NDCA competition in the Southeast, held each spring at the Atlanta Marriott Buckhead. It draws strong Amateur and Pro/Am fields from Georgia, the Carolinas, Tennessee, and Alabama, and is a key regional ranking event for couples pursuing national NDCA Premier points.",
    website:             "https://www.atlantadancesport.com",
    registrationDeadline: null,
    entryFeeMin:         14,
    entryFeeMax:         27,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "carolina-crown-dancesport",
    name:                "Carolina Crown DanceSport",
    dateStart:           null,
    dateEnd:             null,
    typicalMonth:        9,
    venue:               "Charlotte Marriott City Center",
    city:                "Charlotte",
    state:               "North Carolina",
    stateAbbr:           "NC",
    citySlug:            "atlanta",
    region:              "southeast",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["amateur","pro_am"],
    description:         "The Carolina Crown DanceSport is a growing NDCA Premier competition held each fall in Charlotte, NC. It serves as the region's primary ranking event for Amateur and Pro/Am dancers in the Carolinas, Virginia, and Tennessee, offering a well-run competition with a strong sense of community among Southeast ballroom dancers.",
    website:             "https://www.carolinacrowndancesport.com",
    registrationDeadline: null,
    entryFeeMin:         13,
    entryFeeMax:         25,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },

  // ── NORTHEAST ───────────────────────────────────────────────────────────────

  {
    slug:                "new-york-dance-festival",
    name:                "New York Dance Festival",
    dateStart:           "2026-02-26",
    dateEnd:             "2026-03-01",
    typicalMonth:        2,
    venue:               "New York Marriott at the Brooklyn Bridge",
    city:                "New York",
    state:               "New York",
    stateAbbr:           "NY",
    citySlug:            "new-york",
    region:              "northeast",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm","swing"],
    levels:              ["professional","amateur","pro_am"],
    description:         "The New York Dance Festival is one of the most iconic competitions on the East Coast, held each February in New York City. Set in the historic Brooklyn Marriott, it draws an international Professional field alongside competitive Amateur and Pro/Am divisions, with the electric energy of NYC as its backdrop.",
    website:             "https://www.nydancefestival.com",
    registrationUrl:     "https://www.nydancefestival.com/register",
    registrationDeadline: "2026-02-01",
    entryFeeMin:         20,
    entryFeeMax:         40,
    isFeatured:          true,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "manhattan-dance-championships",
    name:                "Manhattan Dance Championships",
    dateStart:           "2026-07-01",
    dateEnd:             "2026-07-05",
    typicalMonth:        7,
    venue:               "New York Marriott at the Brooklyn Bridge",
    city:                "New York",
    state:               "New York",
    stateAbbr:           "NY",
    citySlug:            "new-york",
    region:              "northeast",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm","swing","multi"],
    levels:              ["professional","amateur","pro_am"],
    description:         "The Manhattan Dance Championships is New York City's flagship summer ballroom competition, running across five days each July at the iconic Brooklyn Bridge Marriott. An NDCA Premier national ranking event, it features world-class Professional divisions alongside robust Amateur and Pro/Am fields, and is widely considered one of the best-run events in North America.",
    website:             "https://www.manhattandancechampionships.com",
    registrationUrl:     "https://www.manhattandancechampionships.com/registration",
    registrationDeadline: "2026-05-31",
    entryFeeMin:         20,
    entryFeeMax:         42,
    isFeatured:          true,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "american-star-ball",
    name:                "American Star Ball",
    dateStart:           null,
    dateEnd:             null,
    typicalMonth:        10,
    venue:               "Hilton Parsippany",
    city:                "Parsippany",
    state:               "New Jersey",
    stateAbbr:           "NJ",
    citySlug:            "new-york",
    region:              "northeast",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["professional","amateur","pro_am"],
    description:         "The American Star Ball is one of the oldest and most storied ballroom competitions on the East Coast, held each fall in Parsippany, NJ. An NDCA Premier ranking event, it draws a strong Professional field and competitive Pro/Am couples from the entire Northeast corridor — New York, New Jersey, Pennsylvania, and Connecticut.",
    website:             "https://www.americanstarball.com",
    registrationDeadline: null,
    entryFeeMin:         18,
    entryFeeMax:         36,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "philadelphia-dancesport",
    name:                "Philadelphia DanceSport Championship",
    dateStart:           null,
    dateEnd:             null,
    typicalMonth:        6,
    venue:               "Philadelphia Airport Marriott",
    city:                "Philadelphia",
    state:               "Pennsylvania",
    stateAbbr:           "PA",
    citySlug:            "new-york",
    region:              "northeast",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["amateur","pro_am"],
    description:         "The Philadelphia DanceSport Championship is a respected NDCA Premier competition held each summer, drawing Amateur and Pro/Am competitors from the Mid-Atlantic region. Conveniently located at the Philadelphia Airport Marriott, it offers easy access for dancers from New York, New Jersey, Delaware, Maryland, and Washington DC.",
    website:             "https://www.philadelphiadancesportchampionship.com",
    registrationDeadline: null,
    entryFeeMin:         14,
    entryFeeMax:         27,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "boston-dancesport-challenge",
    name:                "Boston DanceSport Challenge",
    dateStart:           null,
    dateEnd:             null,
    typicalMonth:        1,
    venue:               "Westin Boston Waterfront",
    city:                "Boston",
    state:               "Massachusetts",
    stateAbbr:           "MA",
    citySlug:            "new-york",
    region:              "northeast",
    organization:        "Independent",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["amateur","pro_am"],
    description:         "The Boston DanceSport Challenge is New England's premier independent ballroom competition, drawing Amateur and Pro/Am dancers from Massachusetts, Connecticut, Rhode Island, Vermont, and New Hampshire each January. Set in the heart of Boston at the Westin Waterfront, it offers an elegant competition environment with strong regional participation.",
    website:             "https://www.bostondancesportchallenge.com",
    registrationDeadline: null,
    entryFeeMin:         13,
    entryFeeMax:         25,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "eastern-seaboard-dancesport",
    name:                "Eastern Seaboard DanceSport",
    dateStart:           null,
    dateEnd:             null,
    typicalMonth:        10,
    venue:               "Marriott Bethesda Downtown",
    city:                "Washington",
    state:               "District of Columbia",
    stateAbbr:           "DC",
    citySlug:            "new-york",
    region:              "northeast",
    organization:        "USA Dance",
    styles:              ["standard","latin","smooth","rhythm","swing"],
    levels:              ["amateur","pro_am"],
    description:         "The Eastern Seaboard DanceSport is a premier USA Dance sanctioned competition held each fall in the Washington DC metro area. It draws Amateur and Pro/Am competitors from Maryland, Virginia, DC, Delaware, and Pennsylvania, and serves as an important qualifying event on the USA Dance competition circuit.",
    website:             "https://www.easternseaboarddancesport.com",
    registrationDeadline: null,
    entryFeeMin:         14,
    entryFeeMax:         26,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },
];

// ── Helpers ────────────────────────────────────────────────────────────────────

/** Sort competitions by dateStart ascending (TBA goes to end) */
export function sortedByDate(comps: Competition[]): Competition[] {
  return [...comps].sort((a, b) => {
    if (!a.dateStart && !b.dateStart) return a.typicalMonth - b.typicalMonth;
    if (!a.dateStart) return 1;
    if (!b.dateStart) return -1;
    return new Date(a.dateStart).getTime() - new Date(b.dateStart).getTime();
  });
}

/** Filter helpers */
export function getByRegion(region: string): Competition[] {
  return COMPETITIONS.filter((c) => c.region === region);
}

export function getByStyle(style: string): Competition[] {
  return COMPETITIONS.filter((c) => c.styles.includes(style as any));
}

export function getBySlug(slug: string): Competition | undefined {
  return COMPETITIONS.find((c) => c.slug === slug);
}

export function getFeatured(): Competition[] {
  return COMPETITIONS.filter((c) => c.isFeatured);
}
