// ─── Competition Seed Data ─────────────────────────────────────────────────────
// 30 major recurring US ballroom dance competitions.
// Levels: Professional · Amateur · Pro/Am only (Collegiate + Senior added later).
// dateStart / dateEnd: set to 2026 confirmed dates where known; null = TBA.
// Phase 2 will migrate this to a WordPress CPT (dance_competition post type).

import type { Competition } from "@/types/competition";

export const COMPETITIONS: Competition[] = [

  // ── WEST COAST ──────────────────────────────────────────────────────────────

  {
    slug:                "millennium-dancesport",
    name:                "Millennium DanceSport Championship",
    dateStart:           "2026-06-22",
    dateEnd:             "2026-06-28",
    typicalMonth:        6,
    venue:               "Caribe Royale Orlando",
    city:                "Orlando",
    state:               "Florida",
    stateAbbr:           "FL",
    citySlug:            "miami",
    region:              "southeast",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["professional","amateur","pro_am"],
    description:         "The Millennium DanceSport Championship is one of the largest and most prestigious NDCA Premier competitions in the country, held each June in Orlando, Florida. Drawing top Professional and Pro/Am couples from across North America, it offers intense competition across all four major dance styles in a week-long format.",
    website:             "https://www.m2dance.com",
    registrationUrl:     "https://www.m2dance.com/registration/",
    registrationDeadline: "2026-06-01",
    entryFeeMin:         15,
    entryFeeMax:         30,
    isFeatured:          true,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "desert-classic-dancesport",
    name:                "Desert Classic DanceSport Championships",
    dateStart:           "2026-07-08",
    dateEnd:             "2026-07-12",
    typicalMonth:        7,
    venue:               "JW Marriott Desert Springs Resort & Spa",
    city:                "Palm Desert",
    state:               "California",
    stateAbbr:           "CA",
    citySlug:            "los-angeles",
    region:              "west",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["professional","amateur","pro_am"],
    description:         "The Desert Classic DanceSport Championships is one of the most beloved summer competitions on the NDCA Premier circuit. Held each July at the JW Marriott Desert Springs Resort & Spa in Palm Desert, it attracts world-class professionals alongside hundreds of Pro/Am and Amateur couples in a warm, social atmosphere unlike any other event.",
    website:             "https://www.desertclassicdancesport.com",
    registrationUrl:     "https://www.desertclassicdancesport.com/registration",
    registrationDeadline: "2026-06-15",
    entryFeeMin:         18,
    entryFeeMax:         35,
    isFeatured:          true,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "emerald-ball-dancesport",
    name:                "Emerald Ball DanceSport Championships",
    dateStart:           "2026-04-28",
    dateEnd:             "2026-05-03",
    typicalMonth:        5,
    venue:               "Los Angeles Airport Hilton Hotel",
    city:                "Los Angeles",
    state:               "California",
    stateAbbr:           "CA",
    citySlug:            "los-angeles",
    region:              "west",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm","swing"],
    levels:              ["professional","amateur","pro_am"],
    description:         "The Emerald Ball is one of the most celebrated competitions on the West Coast, running each spring in Los Angeles. Now in its 37th year, it offers a full slate of Professional, Amateur, and Pro/Am divisions across all major styles, drawing competitors and spectators from around the world.",
    website:             "https://www.emeraldball.com",
    registrationUrl:     "https://www.emeraldball.com/register",
    registrationDeadline: "2026-04-10",
    entryFeeMin:         18,
    entryFeeMax:         38,
    isFeatured:          true,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "pacific-coast-classic-dancesport",
    name:                "Pacific Grand Ball DanceSport Championships",
    dateStart:           "2026-05-08",
    dateEnd:             "2026-05-11",
    typicalMonth:        5,
    venue:               "Hyatt Regency at Lake Washington",
    city:                "Renton",
    state:               "Washington",
    stateAbbr:           "WA",
    citySlug:            "seattle",
    region:              "west",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["professional","amateur","pro_am"],
    description:         "The Pacific Grand Ball DanceSport Championships is a premier spring competition on the NDCA circuit, held each May at the Hyatt Regency at Lake Washington near Seattle. Known for its stunning waterfront venue and competitive Professional and Pro/Am fields, it draws dancers from across the Pacific Northwest and California.",
    website:             "https://pgbdancesport.com",
    registrationDeadline: null,
    entryFeeMin:         16,
    entryFeeMax:         32,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "california-star-ball",
    name:                "California Star Ball",
    dateStart:           "2026-11-27",
    dateEnd:             "2026-11-29",
    typicalMonth:        11,
    venue:               "Hilton Santa Barbara Beachfront Resort",
    city:                "Santa Barbara",
    state:               "California",
    stateAbbr:           "CA",
    citySlug:            "los-angeles",
    region:              "west",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["professional","amateur","pro_am"],
    description:         "The California Star Ball is a premier NDCA national ranking event held each Thanksgiving weekend in Santa Barbara. As a key stop on the Best of the Best DanceSport Series leading to Ohio Star Ball, it carries significant ranking points and attracts a highly competitive Pro/Am and Professional field.",
    website:             "https://www.californiastarball.com",
    registrationDeadline: null,
    entryFeeMin:         18,
    entryFeeMax:         36,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "embassy-ball-dancesport",
    name:                "Embassy Ball DanceSport Championships",
    dateStart:           null,
    dateEnd:             null,
    typicalMonth:        9,
    venue:               "Hyatt Regency Orange County",
    city:                "Garden Grove",
    state:               "California",
    stateAbbr:           "CA",
    citySlug:            "los-angeles",
    region:              "west",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["professional","amateur","pro_am"],
    description:         "The Embassy Ball DanceSport Championships is one of the most prestigious competitions in North America, home to multiple World Professional Championship titles. Held each September at the Hyatt Regency Orange County in Garden Grove, CA, it draws international Professional couples and a deep Pro/Am field, making it a must-attend event for serious competitors and spectators alike.",
    website:             "https://www.embassyball.com",
    registrationDeadline: null,
    entryFeeMin:         20,
    entryFeeMax:         40,
    isFeatured:          true,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "san-francisco-open-dancesport",
    name:                "The Ball at the San Francisco Open DanceSport",
    dateStart:           "2026-04-02",
    dateEnd:             "2026-04-05",
    typicalMonth:        4,
    venue:               "Marriott Waterfront Burlingame",
    city:                "Burlingame",
    state:               "California",
    stateAbbr:           "CA",
    citySlug:            "los-angeles",
    region:              "west",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["professional","amateur","pro_am"],
    description:         "The Ball at the San Francisco Open DanceSport is the SF Bay Area's premier Championship DanceSport event, celebrating over 45 years of competition. Held each spring at the Marriott Waterfront Burlingame, it draws Professional, Amateur, and Pro/Am competitors from throughout Northern California, Oregon, and beyond.",
    website:             "https://sfopen.com",
    registrationDeadline: null,
    entryFeeMin:         15,
    entryFeeMax:         28,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "seattle-star-ball",
    name:                "Summit DanceSport",
    dateStart:           "2026-09-24",
    dateEnd:             "2026-09-27",
    typicalMonth:        9,
    venue:               "DoubleTree by Hilton Hotel Seattle Airport",
    city:                "Seattle",
    state:               "Washington",
    stateAbbr:           "WA",
    citySlug:            "seattle",
    region:              "west",
    organization:        "Independent",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["amateur","pro_am"],
    description:         "Summit DanceSport is the Pacific Northwest's premier ballroom dance competition, drawing competitors from Washington, Oregon, British Columbia, and beyond. Known for its welcoming atmosphere and well-organized Pro/Am and Amateur divisions, it's a favorite annual event for dancers throughout the region.",
    website:             "https://summitdancesport.com",
    registrationDeadline: null,
    entryFeeMin:         14,
    entryFeeMax:         26,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },

  // ── MOUNTAIN ────────────────────────────────────────────────────────────────

  {
    slug:                "us-national-amateur-dancesport",
    name:                "US National Amateur DanceSport Championships",
    dateStart:           "2026-03-10",
    dateEnd:             "2026-03-14",
    typicalMonth:        3,
    venue:               "Marriott Provo Hotel & Conference Center",
    city:                "Provo",
    state:               "Utah",
    stateAbbr:           "UT",
    citySlug:            "denver",
    region:              "mountain",
    organization:        "USA Dance",
    styles:              ["standard","latin","smooth","rhythm","swing","country"],
    levels:              ["amateur"],
    description:         "Hosted by BYU DanceSport, the US National Amateur DanceSport Championships is the premier sanctioned amateur competition in the United States, drawing elite amateur couples from every state to compete in Standard, Latin, Smooth, Rhythm, Swing, and Country Western. Qualification for the World Amateur Championships routes through this event.",
    website:             "https://usnationals.byudancesport.com",
    registrationUrl:     "https://usnationals.byudancesport.com/register",
    registrationDeadline: "2026-02-15",
    entryFeeMin:         20,
    entryFeeMax:         40,
    isFeatured:          true,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "denver-dancesport",
    name:                "Colorado Star Ball Championships",
    dateStart:           "2026-06-18",
    dateEnd:             "2026-06-22",
    typicalMonth:        6,
    venue:               "Hyatt Regency Aurora",
    city:                "Denver",
    state:               "Colorado",
    stateAbbr:           "CO",
    citySlug:            "denver",
    region:              "mountain",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["amateur","pro_am"],
    description:         "The Colorado Star Ball Championships is the Mountain West's flagship NDCA competition, held each summer at the Hyatt Regency Denver. With a reputation for exceptional organization and a strong Pro/Am field, it attracts couples from Colorado, Wyoming, Utah, and New Mexico who are building their NDCA Premier ranking.",
    website:             "https://www.coloradostarball.com",
    registrationDeadline: null,
    entryFeeMin:         15,
    entryFeeMax:         28,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },

  // ── SOUTHWEST ───────────────────────────────────────────────────────────────

  {
    slug:                "las-vegas-dancesport",
    name:                "Holiday Dance Classic",
    dateStart:           null,
    dateEnd:             null,
    typicalMonth:        12,
    venue:               "Luxor Las Vegas",
    city:                "Las Vegas",
    state:               "Nevada",
    stateAbbr:           "NV",
    citySlug:            "los-angeles",
    region:              "southwest",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["professional","amateur","pro_am"],
    description:         "The Holiday Dance Classic brings the glitz and energy of Las Vegas to the ballroom dance world each December. An NDCA Premier national ranking event, it attracts Professional and Pro/Am competitors from across the West and Southwest and is known for its spectacular ballroom setting and enthusiastic audience.",
    website:             "https://www.holidaydanceclassic.com",
    registrationDeadline: null,
    entryFeeMin:         16,
    entryFeeMax:         32,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "heritage-classic-dancesport",
    name:                "The Heritage Classic",
    dateStart:           "2026-03-05",
    dateEnd:             "2026-03-07",
    typicalMonth:        3,
    venue:               "Grandover Resort & Spa",
    city:                "Greensboro",
    state:               "North Carolina",
    stateAbbr:           "NC",
    citySlug:            "atlanta",
    region:              "southeast",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm","country"],
    levels:              ["professional","amateur","pro_am"],
    description:         "The Heritage Classic is one of the Southeast's premier NDCA competitions, drawing top Professional and Pro/Am competitors from across the region each spring in Greensboro, NC. It offers divisions across Standard, Latin, Smooth, Rhythm, and Country Western in an elegant competition setting.",
    website:             "https://theheritageclassic.com",
    registrationDeadline: null,
    entryFeeMin:         16,
    entryFeeMax:         30,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "houston-dancesport",
    name:                "Texas Challenge DanceSport",
    dateStart:           "2026-05-08",
    dateEnd:             "2026-05-10",
    typicalMonth:        5,
    venue:               "Marriott Houston at the Texas Medical Center",
    city:                "Houston",
    state:               "Texas",
    stateAbbr:           "TX",
    citySlug:            "houston",
    region:              "southwest",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["amateur","pro_am"],
    description:         "The Texas Challenge DanceSport is a well-regarded NDCA Premier ballroom dance competition held each May at the Marriott Houston at the Texas Medical Center in Houston, Texas. As one of the Southwest's premier NDCA-sanctioned events, Texas Challenge DanceSport draws a strong regional field of Amateur and Pro/Am competitors from Texas, Louisiana, Oklahoma, New Mexico, and Arkansas. The competition is organized into International Standard, International Latin, American Smooth, and American Rhythm style divisions, with Pro/Am scholarship rounds, Amateur championships, and open events scheduled across the three-day weekend. Texas Challenge DanceSport has built a reputation among Houston ballroom dancers and visiting competitors for smooth organization, professional NDCA judging panels, and a welcoming atmosphere that supports first-time competitors and seasoned national-ranking couples alike. Entry fees typically range from $14 to $26 per event, and registration is handled directly through texaschallenge.com. Whether you are an Amateur Open Smooth couple, a Pro/Am Bronze student, or a competitive ballroom dance instructor traveling with students, Texas Challenge DanceSport is the Houston DanceSport event to put on your calendar each spring.",
    website:             "https://www.texaschallenge.com",
    registrationDeadline: null,
    entryFeeMin:         14,
    entryFeeMax:         26,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },

  // ── MIDWEST ─────────────────────────────────────────────────────────────────

  {
    slug:                "chicago-open-dancesport",
    name:                "Chicago DanceSport Championships",
    dateStart:           "2026-10-23",
    dateEnd:             "2026-10-25",
    typicalMonth:        10,
    venue:               "Westin O'Hare",
    city:                "Chicago",
    state:               "Illinois",
    stateAbbr:           "IL",
    citySlug:            "chicago",
    region:              "midwest",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm","swing"],
    levels:              ["professional","amateur","pro_am"],
    description:         "The Chicago DanceSport Championships is one of the Midwest's most prestigious NDCA Premier ranking events, held each fall at the Westin O'Hare. Featuring Professional, Amateur, and Pro/Am divisions, it draws competitors from Illinois, Indiana, Michigan, Ohio, and Wisconsin, and is a major stop for couples building their national ranking.",
    website:             "https://www.chicagodancesportchampionships.com",
    registrationDeadline: null,
    entryFeeMin:         16,
    entryFeeMax:         32,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "indiana-grand-dancesport",
    name:                "Indianapolis Open DanceSport",
    dateStart:           "2026-04-16",
    dateEnd:             "2026-04-18",
    typicalMonth:        4,
    venue:               "Sheraton Indianapolis City Centre Hotel",
    city:                "Indianapolis",
    state:               "Indiana",
    stateAbbr:           "IN",
    citySlug:            "chicago",
    region:              "midwest",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["amateur","pro_am"],
    description:         "The Indianapolis Open DanceSport is a respected NDCA Premier competition held each April in Indianapolis. Known for strong Amateur and Pro/Am participation from across the Midwest, it offers a friendly yet competitive environment and is a popular event for couples working toward national ranking status.",
    website:             "https://www.indianapolisopendancesport.com",
    registrationDeadline: null,
    entryFeeMin:         13,
    entryFeeMax:         24,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "ohio-star-ball",
    name:                "Ohio Star Ball Championships",
    dateStart:           "2026-11-17",
    dateEnd:             "2026-11-22",
    typicalMonth:        11,
    venue:               "Greater Columbus Convention Center",
    city:                "Columbus",
    state:               "Ohio",
    stateAbbr:           "OH",
    citySlug:            "chicago",
    region:              "midwest",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm","swing","country","multi"],
    levels:              ["professional","amateur","pro_am"],
    description:         "The Ohio Star Ball Championships is the most prestigious ballroom dance competition in North America, serving as the season-ending grand finale of the NDCA Premier national ranking circuit. Held each November in Columbus, Ohio, it crowns the Best of the Best Series champions across all styles and levels, drawing hundreds of the world's top Professional and Pro/Am couples.",
    website:             "https://ohiostarball.com",
    registrationUrl:     "https://ohiostarball.com/osb-registration",
    registrationDeadline: "2026-10-31",
    entryFeeMin:         22,
    entryFeeMax:         45,
    isFeatured:          true,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "minnesota-star-ball",
    name:                "The Snow Ball DanceSport",
    dateStart:           null,
    dateEnd:             null,
    typicalMonth:        2,
    venue:               "DoubleTree by Hilton Bloomington",
    city:                "Minneapolis",
    state:               "Minnesota",
    stateAbbr:           "MN",
    citySlug:            "chicago",
    region:              "midwest",
    organization:        "Independent",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["amateur","pro_am"],
    description:         "The Snow Ball DanceSport is the Twin Cities' premier independent ballroom competition, drawing Amateur and Pro/Am dancers from Minnesota, Wisconsin, Iowa, and the Dakotas each February. Celebrated for its warm community atmosphere and excellent production, it's a standout event in the upper Midwest ballroom calendar.",
    website:             "https://www.thesnowballcomp.com",
    registrationDeadline: null,
    entryFeeMin:         13,
    entryFeeMax:         24,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },

  // ── SOUTHEAST ───────────────────────────────────────────────────────────────

  {
    slug:                "usa-dance-nationals",
    name:                "USA Dance National DanceSport Championships",
    dateStart:           "2026-03-27",
    dateEnd:             "2026-03-29",
    typicalMonth:        3,
    venue:               "David L. Lawrence Convention Center",
    city:                "Pittsburgh",
    state:               "Pennsylvania",
    stateAbbr:           "PA",
    citySlug:            "chicago",
    region:              "northeast",
    organization:        "USA Dance",
    styles:              ["standard","latin","smooth","rhythm","swing","country","multi"],
    levels:              ["amateur","pro_am"],
    description:         "The USA Dance National DanceSport Championships is the culminating event of the USA Dance sanctioned competition season. Held in Pittsburgh, it brings together the nation's best Amateur and Pro/Am competitors across all styles and serves as the primary pathway for selection to the Pan American Games and World Championships.",
    website:             "https://usadancenationals.org",
    registrationUrl:     "https://usadancenationals.org/register",
    registrationDeadline: "2026-03-01",
    entryFeeMin:         18,
    entryFeeMax:         36,
    isFeatured:          true,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "united-states-dance-championships",
    name:                "United States Dance Championships",
    dateStart:           "2026-09-07",
    dateEnd:             "2026-09-12",
    typicalMonth:        9,
    venue:               "Rosen Shingle Creek Resort",
    city:                "Orlando",
    state:               "Florida",
    stateAbbr:           "FL",
    citySlug:            "miami",
    region:              "southeast",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm","swing","country","multi"],
    levels:              ["professional","amateur","pro_am"],
    description:         "The United States Dance Championships in Orlando is one of the most comprehensive ballroom competitions in North America, offering divisions in every major style and level across an extended multi-day format. Held each September at the Rosen Shingle Creek Resort, it attracts international professionals and a massive Pro/Am field for a truly world-class event.",
    website:             "https://unitedstatesdancechampionships.com",
    registrationDeadline: null,
    entryFeeMin:         20,
    entryFeeMax:         42,
    isFeatured:          true,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "grand-nationals-dancesport",
    name:                "The Grand National Championships",
    dateStart:           "2026-10-29",
    dateEnd:             "2026-10-31",
    typicalMonth:        10,
    venue:               "Doral National Resort & Spa",
    city:                "Miami",
    state:               "Florida",
    stateAbbr:           "FL",
    citySlug:            "miami",
    region:              "southeast",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["professional","amateur","pro_am"],
    description:         "The Grand National Championships is one of Florida's most prestigious dance competitions, held each October at the Doral National Resort & Spa in Miami. Home to multiple WDC World Professional Championships, it draws an elite international Professional field alongside a highly competitive Pro/Am division.",
    website:             "https://www.grandnationalchampionship.com",
    registrationDeadline: null,
    entryFeeMin:         18,
    entryFeeMax:         38,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "hollywood-dancesport",
    name:                "Hollywood DanceSport Championships",
    dateStart:           null,
    dateEnd:             null,
    typicalMonth:        11,
    venue:               "Hyatt Regency LAX",
    city:                "Los Angeles",
    state:               "California",
    stateAbbr:           "CA",
    citySlug:            "los-angeles",
    region:              "west",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["professional","amateur","pro_am"],
    description:         "The Hollywood DanceSport Championships is a premier West Coast NDCA competition held each fall at the Hyatt Regency LAX in Los Angeles. Known for strong Professional and Pro/Am divisions across all major styles, it draws competitors and spectators from across California and the western United States.",
    website:             "https://www.hollywooddancesport.com",
    registrationDeadline: null,
    entryFeeMin:         17,
    entryFeeMax:         34,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "atlanta-dancesport",
    name:                "Atlanta Open DanceSport Spectacular",
    dateStart:           "2026-05-07",
    dateEnd:             "2026-05-10",
    typicalMonth:        5,
    venue:               "Crowne Plaza Atlanta Perimeter at Ravinia",
    city:                "Atlanta",
    state:               "Georgia",
    stateAbbr:           "GA",
    citySlug:            "atlanta",
    region:              "southeast",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["amateur","pro_am"],
    description:         "The Atlanta Open DanceSport Spectacular is the premier NDCA competition in the Southeast, held each spring at the Atlanta Marriott Buckhead. It draws strong Amateur and Pro/Am fields from Georgia, the Carolinas, Tennessee, and Alabama, and is a key regional ranking event for couples pursuing national NDCA Premier points.",
    website:             "https://www.atlantaopen.com",
    registrationDeadline: null,
    entryFeeMin:         14,
    entryFeeMax:         27,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "carolina-crown-dancesport",
    name:                "Crown of Carolina DanceSport Classic",
    dateStart:           "2026-05-24",
    dateEnd:             "2026-05-24",
    typicalMonth:        5,
    venue:               "Charlotte Marriott City Center",
    city:                "Charlotte",
    state:               "North Carolina",
    stateAbbr:           "NC",
    citySlug:            "atlanta",
    region:              "southeast",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["amateur","pro_am"],
    description:         "The Crown of Carolina DanceSport Classic is a growing NDCA Premier competition held each spring in Charlotte, NC. It serves as the region's primary ranking event for Amateur and Pro/Am dancers in the Carolinas, Virginia, and Tennessee, offering a well-run competition with a strong sense of community among Southeast ballroom dancers.",
    website:             "https://northcarolinaopen.com",
    registrationDeadline: null,
    entryFeeMin:         13,
    entryFeeMax:         25,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },

  // ── NORTHEAST ───────────────────────────────────────────────────────────────

  {
    slug:                "new-york-dance-festival",
    name:                "New York Dance Festival",
    dateStart:           "2026-02-26",
    dateEnd:             "2026-03-01",
    typicalMonth:        2,
    venue:               "New York Hilton Midtown",
    city:                "New York",
    state:               "New York",
    stateAbbr:           "NY",
    citySlug:            "new-york",
    region:              "northeast",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm","swing"],
    levels:              ["professional","amateur","pro_am"],
    description:         "The New York Dance Festival is one of the most iconic competitions on the East Coast, held each February in New York City. Now at the New York Hilton Midtown's Grand Ballroom, it draws an international Professional field alongside competitive Amateur and Pro/Am divisions, with the electric energy of NYC as its backdrop.",
    website:             "https://www.nydancefestival.com",
    registrationUrl:     "https://www.nydancefestival.com/register",
    registrationDeadline: "2026-02-01",
    entryFeeMin:         20,
    entryFeeMax:         40,
    isFeatured:          true,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "manhattan-dance-championships",
    name:                "Manhattan Dance Championships",
    dateStart:           "2026-07-01",
    dateEnd:             "2026-07-05",
    typicalMonth:        7,
    venue:               "New York Marriott at the Brooklyn Bridge",
    city:                "New York",
    state:               "New York",
    stateAbbr:           "NY",
    citySlug:            "new-york",
    region:              "northeast",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm","swing","multi"],
    levels:              ["professional","amateur","pro_am"],
    description:         "The Manhattan Dance Championships is New York City's flagship summer ballroom competition, running across five days each July at the iconic Brooklyn Bridge Marriott. An NDCA Premier national ranking event, it features world-class Professional divisions alongside robust Amateur and Pro/Am fields, and is widely considered one of the best-run events in North America.",
    website:             "https://www.manhattandancechampionships.com",
    registrationUrl:     "https://www.manhattandancechampionships.com/registration",
    registrationDeadline: "2026-05-31",
    entryFeeMin:         20,
    entryFeeMax:         42,
    isFeatured:          true,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "american-star-ball",
    name:                "American Star Ball",
    dateStart:           "2026-05-14",
    dateEnd:             "2026-05-17",
    typicalMonth:        5,
    venue:               "Resorts Casino Hotel",
    city:                "Atlantic City",
    state:               "New Jersey",
    stateAbbr:           "NJ",
    citySlug:            "new-york",
    region:              "northeast",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["professional","amateur","pro_am"],
    description:         "The American Star Ball is one of the oldest and most storied ballroom competitions on the East Coast, held each spring at Resorts Casino Hotel in Atlantic City, NJ. An NDCA Premier ranking event, it draws a strong Professional field and competitive Pro/Am couples from the entire Northeast corridor — New York, New Jersey, Pennsylvania, and Connecticut.",
    website:             "https://www.americanstarball.com",
    registrationDeadline: null,
    entryFeeMin:         18,
    entryFeeMax:         36,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "philadelphia-dancesport",
    name:                "Philadelphia DanceSport Championship",
    dateStart:           "2026-04-09",
    dateEnd:             "2026-04-12",
    typicalMonth:        4,
    venue:               "Hilton Philadelphia at Penn's Landing",
    city:                "Philadelphia",
    state:               "Pennsylvania",
    stateAbbr:           "PA",
    citySlug:            "new-york",
    region:              "northeast",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["amateur","pro_am"],
    description:         "The Philadelphia DanceSport Championship is a respected NDCA Premier competition held each spring, drawing Amateur and Pro/Am competitors from the Mid-Atlantic region. Located at the Hilton Philadelphia at Penn's Landing, it offers easy access for dancers from New York, New Jersey, Delaware, Maryland, and Washington DC.",
    website:             "https://www.philadelphiadancesportchampionship.com",
    registrationDeadline: null,
    entryFeeMin:         14,
    entryFeeMax:         27,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "boston-dancesport-challenge",
    name:                "Boston DanceSport Cup",
    dateStart:           "2026-01-24",
    dateEnd:             "2026-01-24",
    typicalMonth:        1,
    venue:               "Hilton Boston-Woburn",
    city:                "Boston",
    state:               "Massachusetts",
    stateAbbr:           "MA",
    citySlug:            "new-york",
    region:              "northeast",
    organization:        "Independent",
    styles:              ["standard","latin","smooth","rhythm"],
    levels:              ["amateur","pro_am"],
    description:         "The Boston DanceSport Cup is New England's premier independent ballroom competition, celebrating dancers of all ages and levels each January. Held at the Hilton Boston-Woburn, it draws Amateur and Pro/Am dancers from Massachusetts, Connecticut, Rhode Island, Vermont, and New Hampshire.",
    website:             "https://www.bostondancesportcup.com",
    registrationDeadline: null,
    entryFeeMin:         13,
    entryFeeMax:         25,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },

  {
    slug:                "eastern-seaboard-dancesport",
    name:                "Eastern United States DanceSport Championships",
    dateStart:           null,
    dateEnd:             null,
    typicalMonth:        1,
    venue:               "DoubleTree by Hilton Newark",
    city:                "Newark",
    state:               "New Jersey",
    stateAbbr:           "NJ",
    citySlug:            "new-york",
    region:              "northeast",
    organization:        "NDCA",
    styles:              ["standard","latin","smooth","rhythm","swing"],
    levels:              ["professional","amateur","pro_am"],
    description:         "The Eastern United States DanceSport Championships is one of the longest-running ballroom competitions in North America, with a history dating back to 1968. Held each January in the New York-New Jersey metro area, it draws Professional, Amateur, and Pro/Am competitors from across the entire Northeast and Mid-Atlantic region.",
    website:             "https://www.easternunitedstateschampionships.com",
    registrationDeadline: null,
    entryFeeMin:         14,
    entryFeeMax:         26,
    isFeatured:          false,
    isRecurring:         true,
    tier:                "free",
  },
];

// ── Helpers ────────────────────────────────────────────────────────────────────

/** Sort competitions by dateStart ascending (TBA goes to end) */
export function sortedByDate(comps: Competition[]): Competition[] {
  return [...comps].sort((a, b) => {
    if (!a.dateStart && !b.dateStart) return a.typicalMonth - b.typicalMonth;
    if (!a.dateStart) return 1;
    if (!b.dateStart) return -1;
    return new Date(a.dateStart).getTime() - new Date(b.dateStart).getTime();
  });
}

/** Filter helpers */
export function getByRegion(region: string): Competition[] {
  return COMPETITIONS.filter((c) => c.region === region);
}

export function getByStyle(style: string): Competition[] {
  return COMPETITIONS.filter((c) => c.styles.includes(style as any));
}

export function getBySlug(slug: string): Competition | undefined {
  return COMPETITIONS.find((c) => c.slug === slug);
}

export function getFeatured(): Competition[] {
  return COMPETITIONS.filter((c) => c.isFeatured);
}