/**
 * SEO Introductory Copy
 * City-specific and state-specific content for eco-friendly pest control
 * search engine indexing and user engagement on landing pages.
 */

// ─────────────────────────────────────────────────────────────────────────────
// CITY INTRO COPY
// ─────────────────────────────────────────────────────────────────────────────

const CITY_INTRO_COPY: Record<string, string> = {
  houston: `Houston's warm, humid climate creates year-round pressure from mosquitoes, termites, and fire ants — making eco-friendly pest control not just a preference but a necessity for families near bayous and green spaces. Discover companies using botanical treatments, integrated pest management, and targeted biological controls that protect your home without compromising Houston's sensitive wetland ecosystems.`,
  dallas: `Dallas homeowners face persistent challenges from termites, roaches, and seasonal ant invasions driven by the North Texas heat. Eco-friendly pest control companies in Dallas leverage heat treatments, borate-based termite barriers, and low-toxicity baiting systems that keep families and pets safe while delivering lasting results across the Metroplex.`,
  phoenix: `Phoenix's desert environment harbors scorpions, bark scorpions, termites, and black widows that thrive in the extreme heat. Eco-friendly pest control providers in the Valley of the Sun specialize in perimeter sealing, diatomaceous earth applications, and habitat modification techniques that reduce pest populations without introducing harsh chemicals into the arid landscape.`,
  "las-vegas": `Las Vegas deals with scorpions, roof rats, and cockroaches that flourish in the desert climate and seek shelter in air-conditioned homes. Green pest control companies in the Las Vegas Valley use exclusion methods, essential oil-based repellents, and targeted IPM strategies that keep pests out while protecting the fragile Mojave Desert ecosystem.`,
  miami: `Miami's tropical climate is a magnet for German cockroaches, fire ants, mosquitoes, and subterranean termites that cause billions in damage across South Florida annually. Eco-friendly pest control companies here deploy mosquito larvicides, orange oil termite treatments, and botanical sprays that are effective in the heat and humidity while keeping Miami's coastal waterways clean.`,
  atlanta: `Atlanta's lush tree canopy and warm, humid summers create ideal conditions for mosquitoes, carpenter ants, termites, and brown recluse spiders. Green pest control providers across Metro Atlanta use targeted baiting systems, beneficial nematodes, and moisture management techniques that address pest problems at their source without broad-spectrum chemical applications.`,
  orlando: `Orlando's subtropical environment supports year-round pest activity, from drywood termites and palmetto bugs to fire ants and whiteflies that damage ornamental plants. Eco-friendly pest control companies in Central Florida specialize in tent-free termite treatments, organic lawn pest management, and integrated approaches that protect both homes and the region's sensitive aquifer system.`,
  tampa: `Tampa Bay's Gulf Coast humidity drives persistent problems with subterranean termites, mosquitoes, and American cockroaches that invade homes from crawl spaces and storm drains. Green pest control providers in the Tampa area use borate wood treatments, BTI mosquito dunks, and exclusion-based rodent control that safeguard families without contaminating Tampa Bay's marine ecosystem.`,
  "san-antonio": `San Antonio contends with fire ants, scorpions, and aggressive Formosan termite colonies fueled by the South Texas warmth and moisture. Eco-friendly pest control companies in the Alamo City employ fire ant broadcasting with spinosad-based baits, UV light traps, and organic barrier treatments that protect homes and the historic River Walk district's delicate ecosystem.`,
  charlotte: `Charlotte's Piedmont location brings a mix of termites, mosquitoes, carpenter bees, and brown recluse spiders that become especially active during the long Southern summers. Green pest control providers in the Charlotte metro use targeted bait stations, botanical perimeter sprays, and moisture-reduction strategies that address the root causes of infestations sustainably.`,
  raleigh: `Raleigh's position in the Research Triangle brings both suburban pest challenges and wooded-lot wildlife conflicts, from termites and fire ants to occasional copperhead encounters. Eco-friendly pest control companies in the Triangle area focus on habitat modification, pheromone-based monitoring traps, and low-impact treatments that align with the region's environmentally conscious culture.`,
  nashville: `Nashville's warm, wet springs and mild winters create breeding grounds for mosquitoes, brown recluse spiders, and Eastern subterranean termites throughout Middle Tennessee. Green pest control providers in Music City use essential oil barriers, targeted heat treatments, and biological pest controls that keep homes protected without the heavy chemical footprint of conventional methods.`,
  austin: `Austin's explosive growth has pushed neighborhoods into habitats shared with fire ants, scorpions, and Formosan termites that thrive in Central Texas limestone terrain. Eco-friendly pest control companies in the Austin area align with the city's green ethos, offering cedar oil treatments, beneficial insect releases, and integrated pest management programs that protect both homes and Barton Springs' watershed.`,
  jacksonville: `Jacksonville's coastal humidity and sprawling footprint make it a hotspot for mosquitoes, termites, and rodents that invade homes from the surrounding maritime forests and marshlands. Green pest control providers in Northeast Florida use tidal-zone-safe mosquito treatments, orange oil termite solutions, and exclusion-first rodent strategies that protect the St. Johns River ecosystem.`,
  "new-orleans": `New Orleans faces some of the most intense pest pressure in the nation — Formosan termites, mosquitoes, cockroaches, and rodents thrive in the city's subtropical humidity and aging building stock. Eco-friendly pest control companies in the Crescent City use sentricon termite systems, BTI larvicides, and botanical sprays that combat persistent infestations while safeguarding the unique wetland environment surrounding the city.`,
  "san-diego": `San Diego's mild Mediterranean climate keeps pest activity moderate but persistent, with Argentine ants, black widows, and drywood termites topping the list of common invaders. Green pest control providers in San Diego County use localized fumigation alternatives, botanical barrier sprays, and ant colony exclusion techniques that protect homes while respecting the region's coastal and canyon ecosystems.`,
  denver: `Denver's semi-arid climate brings seasonal waves of boxelder bugs, miller moths, and field mice seeking shelter from the mountain cold, along with occasional wasp and spider problems. Eco-friendly pest control companies along the Front Range use exclusion sealing, peppermint oil deterrents, and targeted trapping that handles Colorado's unique pest mix without relying on broad-spectrum chemical treatments.`,
  seattle: `Seattle's damp Pacific Northwest climate creates ideal conditions for carpenter ants, moisture-loving rodents, and silverfish that damage homes from the inside out. Green pest control providers in the Puget Sound region specialize in moisture management, bait station networks, and botanical treatments that address the root causes of infestations without harming Seattle's lush urban forests and salmon-bearing waterways.`,
  portland: `Portland's wet winters and mild summers fuel persistent problems with carpenter ants, rats, slugs, and moisture-dependent pests that exploit the city's older housing stock. Eco-friendly pest control companies in the Rose City use snap-trap rodent programs, boric acid treatments, and habitat modification techniques that reflect Portland's strong environmental values and protect the Willamette River watershed.`,
  chicago: `Chicago's extreme temperature swings drive seasonal pest invasions — mice and rats in winter, mosquitoes and wasps in summer, and cockroaches and bed bugs year-round in the city's dense housing. Green pest control providers across Chicagoland use IPM-first approaches, gel bait roach treatments, and exclusion-based rodent control that address pest problems effectively in both single-family homes and multi-unit buildings.`,
  "los-angeles": `Los Angeles contends with Argentine ants, black widows, drywood termites, and roof rats that thrive across the basin's diverse microclimates. Eco-friendly pest control companies throughout LA County use heat treatments for termites, essential oil perimeter barriers, and exclusion-first rodent management that protect homes from the Westside to the San Gabriel Valley without adding chemicals to the region's stressed watershed system.`,
};

// Fallback copy for cities not explicitly listed
const CITY_INTRO_FALLBACK = (cityName: string) =>
  `Discover eco-friendly pest control companies in ${cityName}. Our curated directory features providers who use green, low-toxicity methods — including integrated pest management, botanical treatments, and exclusion techniques — to protect your home and family from common pests without harsh chemicals. Find a trusted eco-friendly exterminator near you today.`;

export function getCityIntroCopy(city: string): string {
  const cityName = city
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");

  return CITY_INTRO_COPY[city] || CITY_INTRO_FALLBACK(cityName);
}

// ─────────────────────────────────────────────────────────────────────────────
// STATE INTRO COPY
// ─────────────────────────────────────────────────────────────────────────────

const STATE_INTRO_COPY: Record<string, string> = {
  texas: `Texas faces an intense year-round pest landscape driven by heat, humidity, and vast geography — from Formosan termites devastating Gulf Coast homes to fire ants blanketing suburban lawns and scorpions in the Hill Country. Eco-friendly pest control companies across the Lone Star State use targeted baiting, heat treatments, and biological controls that handle Texas-sized pest problems without broad-spectrum chemicals.`,
  florida: `Florida's subtropical climate makes it one of the most pest-challenged states in the nation, with subterranean termites, mosquitoes, palmetto bugs, and invasive species like the Asian citrus psyllid creating constant pressure. Green pest control providers throughout the Sunshine State specialize in moisture management, tent-free termite alternatives, and larvicide programs that protect homes and Florida's fragile aquifer system.`,
  california: `California's diverse climate zones — from coastal fog to desert heat — create pest challenges ranging from drywood termites and Argentine ants in Southern California to gophers and yellow jackets in the north. Eco-friendly pest control companies statewide leverage the state's progressive pesticide regulations and offer IPM-first approaches, heat fumigation, and botanical treatments that meet California's strict environmental standards.`,
  georgia: `Georgia's hot, humid summers and mild winters sustain year-round pressure from mosquitoes, termites, fire ants, and brown recluse spiders across the Peach State. Green pest control providers from Atlanta to Savannah use botanical perimeter treatments, beneficial nematodes for fire ant control, and moisture management strategies that protect homes without contaminating Georgia's rivers and coastal marshlands.`,
  arizona: `Arizona's desert environment harbors bark scorpions, black widows, Africanized bees, and subterranean termites that cause significant damage across the Sun Belt. Eco-friendly pest control companies throughout Arizona use perimeter exclusion, diatomaceous earth, and targeted UV trapping that address the state's unique pest mix while preserving the fragile Sonoran Desert ecosystem.`,
  "north-carolina": `North Carolina's varied terrain — from the Blue Ridge Mountains to the Outer Banks — produces diverse pest challenges including termites, mosquitoes, fire ants, and carpenter bees. Green pest control providers across the Tar Heel State use regionally adapted IPM programs, bait-based termite management, and botanical sprays that protect homes from the Piedmont to the coast.`,
  tennessee: `Tennessee's warm, humid climate fosters persistent problems with termites, mosquitoes, brown recluse spiders, and carpenter ants from Memphis to Knoxville. Eco-friendly pest control companies across the Volunteer State employ essential oil barriers, heat treatments, and exclusion-based methods that handle the state's pest challenges without harsh chemical applications in homes and schools.`,
  colorado: `Colorado's semi-arid climate and dramatic elevation changes create a unique pest landscape — miller moths and boxelder bugs at lower elevations, mice seeking winter shelter, and occasional yellow jacket nests in mountain communities. Green pest control providers along the Front Range and beyond use exclusion sealing, peppermint-based deterrents, and targeted trapping suited to Colorado's environmentally conscious residents.`,
  washington: `Washington State's wet western climate and dry eastern plateau create distinct pest zones — carpenter ants and moisture-loving rodents west of the Cascades, and spiders and occasional wasp infestations in the drier east. Eco-friendly pest control companies throughout the Evergreen State prioritize moisture management, botanical treatments, and habitat modification that protect both homes and salmon-bearing waterways.`,
  oregon: `Oregon's Pacific Northwest dampness fuels year-round activity from carpenter ants, rats, silverfish, and moisture-dependent wood-destroying organisms. Green pest control providers across the Beaver State use snap-trap rodent programs, boric acid treatments, and exclusion techniques that reflect Oregon's environmental leadership and protect the state's rivers, forests, and urban tree canopy.`,
  "new-york": `New York's dense urban areas and rural regions face very different pest challenges — bed bugs and cockroaches in the city, termites and carpenter ants upstate, and rodents everywhere in between. Eco-friendly pest control companies across the Empire State use gel baits, heat treatments, and IPM strategies that address infestations effectively in everything from high-rise apartments to colonial-era homes.`,
  illinois: `Illinois experiences intense seasonal pest cycles — rodent invasions in harsh winters, mosquito swarms in humid summers, and termite pressure year-round in the state's clay-heavy soils. Green pest control providers from Chicago to Springfield use exclusion-based rodent control, BTI mosquito treatments, and bait station termite monitoring that protect homes across the Prairie State sustainably.`,
  ohio: `Ohio's four-season climate brings seasonal invasions of stink bugs, ladybugs, and mice in fall and winter, plus mosquitoes, yellow jackets, and carpenter ants in the warmer months. Eco-friendly pest control companies across the Buckeye State use IPM-first approaches, botanical barrier sprays, and exclusion techniques that handle Ohio's diverse pest mix without over-relying on chemical treatments.`,
  pennsylvania: `Pennsylvania homeowners face termites in the southeast, stink bug invasions statewide, and rodent pressure in both urban Philadelphia and rural areas. Green pest control providers across the Keystone State use pheromone traps for stink bugs, bait-based termite monitoring, and exclusion-first rodent strategies that address the state's varied pest challenges with minimal environmental impact.`,
  virginia: `Virginia's mid-Atlantic location brings a full spectrum of pest challenges — from termites and mosquitoes in the Tidewater region to carpenter ants and brown recluse spiders in the western mountains. Eco-friendly pest control companies across the Commonwealth use regionally targeted IPM programs, botanical treatments, and moisture management that protect homes from Richmond to Roanoke.`,
  maryland: `Maryland's humid Chesapeake Bay climate fuels persistent mosquito, termite, and rodent problems, with stink bugs adding seasonal misery across the state. Green pest control providers throughout the Old Line State prioritize Chesapeake Bay-safe treatments, using botanical sprays, exclusion methods, and biological controls that reduce pest populations without contributing to the bay's water quality challenges.`,
  massachusetts: `Massachusetts faces seasonal pest waves — carpenter ants and termites in spring, mosquitoes and ticks carrying Lyme disease in summer, and mice seeking warmth in historic homes come fall. Eco-friendly pest control companies across the Bay State use tick tubes, targeted bait stations, and exclusion techniques that protect both families and the region's sensitive coastal and woodland ecosystems.`,
  "new-jersey": `New Jersey's dense population and varied geography create concentrated pest pressure — from termites in the Pine Barrens to mosquitoes in the shore communities and rodents throughout the urban corridor. Green pest control providers across the Garden State use monitoring-based termite programs, larvicide treatments, and IPM strategies tailored to New Jersey's mix of suburban, urban, and coastal environments.`,
  michigan: `Michigan's Great Lakes climate brings seasonal carpenter ant infestations, boxelder bug invasions, and persistent rodent problems as temperatures swing between humid summers and bitter winters. Eco-friendly pest control companies across the Wolverine State use exclusion sealing, botanical perimeter treatments, and moisture management that address pest entry points without chemical overspray near Michigan's lakes and rivers.`,
  minnesota: `Minnesota's extreme winters drive mice, boxelder bugs, and cluster flies indoors, while warm summers bring mosquitoes, wasps, and carpenter ants. Green pest control providers across the North Star State use exclusion-first strategies, essential oil deterrents, and BTI-based mosquito programs that handle the state's seasonal pest cycles without harsh chemicals in the Land of 10,000 Lakes.`,
  indiana: `Indiana's agricultural landscape and humid summers create persistent problems with field mice, mosquitoes, termites, and brown recluse spiders across the Hoosier State. Eco-friendly pest control companies throughout Indiana use bait station monitoring, botanical barriers, and habitat modification techniques that protect homes and farms without broad-spectrum pesticide applications.`,
  missouri: `Missouri's central location brings both Southern and Northern pest challenges — termites and brown recluse spiders thrive in the warm, humid summers, while mice and cockroaches invade homes during cold winters. Green pest control providers across the Show-Me State use heat treatments, glue board monitoring, and targeted baiting that address Missouri's diverse pest mix sustainably.`,
  wisconsin: `Wisconsin's cold winters drive rodents, boxelder bugs, and Asian lady beetles indoors, while summers bring mosquitoes, wasps, and carpenter ants to the state's lake-heavy landscape. Eco-friendly pest control companies across the Badger State use exclusion techniques, pheromone-based trapping, and botanical treatments that protect homes without contaminating Wisconsin's cherished lakes and waterways.`,
  louisiana: `Louisiana faces some of the nation's most intense pest pressure — Formosan termites cause hundreds of millions in damage annually, while mosquitoes, cockroaches, and fire ants thrive in the state's subtropical humidity. Green pest control providers across the Pelican State use sentricon monitoring systems, BTI larvicides, and botanical treatments that combat relentless pest activity while protecting Louisiana's bayous and wetlands.`,
  "south-carolina": `South Carolina's Lowcountry humidity and coastal geography create ideal conditions for termites, mosquitoes, fire ants, and palmetto bugs that challenge homeowners from Charleston to Greenville. Eco-friendly pest control companies across the Palmetto State use moisture management, orange oil termite treatments, and biological mosquito controls that protect homes without harming the state's marshes and barrier island ecosystems.`,
  alabama: `Alabama's long, hot summers and mild winters sustain year-round termite, mosquito, and fire ant activity that puts the Yellowhammer State among the most pest-challenged in the Southeast. Green pest control providers throughout Alabama use baiting systems, larvicide programs, and botanical treatments that address persistent pest pressure without contributing to runoff in the state's rivers and Mobile Bay watershed.`,
  oklahoma: `Oklahoma's variable climate — from humid eastern forests to dry western plains — produces a pest mix including brown recluse spiders, termites, scorpions, and seasonal mosquito swarms. Eco-friendly pest control companies across the Sooner State use regionally adapted IPM programs, exclusion sealing, and low-toxicity treatments that handle Oklahoma's diverse pest challenges without unnecessary chemical exposure.`,
  kentucky: `Kentucky's warm, humid conditions foster termites, carpenter ants, brown recluse spiders, and seasonal mosquito populations throughout the Bluegrass State. Green pest control providers from Louisville to Lexington use bait-based termite monitoring, botanical perimeter sprays, and moisture management strategies that protect homes and Kentucky's limestone cave ecosystems from chemical contamination.`,
  connecticut: `Connecticut's older housing stock and wooded suburban lots create persistent challenges with termites, carpenter ants, ticks carrying Lyme disease, and mice that exploit gaps in aging foundations. Eco-friendly pest control companies across the Nutmeg State use tick tube programs, exclusion-based rodent control, and monitoring-focused termite management that protect families and the Long Island Sound watershed.`,
  nevada: `Nevada's desert climate drives scorpions, black widows, roof rats, and occasional bark beetle infestations, with pests seeking water and shelter in residential areas across the Silver State. Green pest control providers from Las Vegas to Reno use exclusion sealing, diatomaceous earth, and UV light trapping that manage desert pest populations without introducing harsh chemicals into Nevada's fragile arid environment.`,
};

// Fallback copy for states not explicitly listed
const STATE_INTRO_FALLBACK = (stateName: string) =>
  `Find eco-friendly pest control companies across ${stateName}. Our directory features providers committed to green, low-toxicity methods — including integrated pest management, botanical treatments, and humane exclusion techniques — that protect your home and family from local pests without relying on harsh chemicals. Browse trusted eco-friendly exterminators in ${stateName} today.`;

export function getStateIntroCopy(stateSlug: string): string {
  const stateName = stateSlug
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");

  return STATE_INTRO_COPY[stateSlug] || STATE_INTRO_FALLBACK(stateName);
}
