/**
 * SEO Introductory Copy
 * City-specific and state-specific content for eco-friendly pest control
 * search engine indexing and user engagement on landing pages.
 */

// ─────────────────────────────────────────────────────────────────────────────
// CITY INTRO COPY
// ─────────────────────────────────────────────────────────────────────────────

const CITY_INTRO_COPY: Record<string, string> = {
  houston: `Houston's warm, humid climate creates year-round pressure from mosquitoes, termites, and fire ants — making eco-friendly pest control not just a preference but a necessity for families near bayous and green spaces. Discover companies using botanical treatments, integrated pest management, and targeted biological controls that protect your home without compromising Houston's sensitive wetland ecosystems.`,
  dallas: `Dallas homeowners face persistent challenges from termites, roaches, and seasonal ant invasions driven by the North Texas heat. Eco-friendly pest control companies in Dallas leverage heat treatments, borate-based termite barriers, and low-toxicity baiting systems that keep families and pets safe while delivering lasting results across the Metroplex.`,
  phoenix: `Phoenix's desert environment harbors scorpions, bark scorpions, termites, and black widows that thrive in the extreme heat. Eco-friendly pest control providers in the Valley of the Sun specialize in perimeter sealing, diatomaceous earth applications, and habitat modification techniques that reduce pest populations without introducing harsh chemicals into the arid landscape.`,
  "las-vegas": `Las Vegas deals with scorpions, roof rats, and cockroaches that flourish in the desert climate and seek shelter in air-conditioned homes. Green pest control companies in the Las Vegas Valley use exclusion methods, essential oil-based repellents, and targeted IPM strategies that keep pests out while protecting the fragile Mojave Desert ecosystem.`,
  miami: `Miami's tropical climate is a magnet for German cockroaches, fire ants, mosquitoes, and subterranean termites that cause billions in damage across South Florida annually. Eco-friendly pest control companies here deploy mosquito larvicides, orange oil termite treatments, and botanical sprays that are effective in the heat and humidity while keeping Miami's coastal waterways clean.`,
  atlanta: `Atlanta's lush tree canopy and warm, humid summers create ideal conditions for mosquitoes, carpenter ants, termites, and brown recluse spiders. Green pest control providers across Metro Atlanta use targeted baiting systems, beneficial nematodes, and moisture management techniques that address pest problems at their source without broad-spectrum chemical applications.`,
  orlando: `Orlando's subtropical environment supports year-round pest activity, from drywood termites and palmetto bugs to fire ants and whiteflies that damage ornamental plants. Eco-friendly pest control companies in Central Florida specialize in tent-free termite treatments, organic lawn pest management, and integrated approaches that protect both homes and the region's sensitive aquifer system.`,
  tampa: `Tampa Bay's Gulf Coast humidity drives persistent problems with subterranean termites, mosquitoes, and American cockroaches that invade homes from crawl spaces and storm drains. Green pest control providers in the Tampa area use borate wood treatments, BTI mosquito dunks, and exclusion-based rodent control that safeguard families without contaminating Tampa Bay's marine ecosystem.`,
  "san-antonio": `San Antonio contends with fire ants, scorpions, and aggressive Formosan termite colonies fueled by the South Texas warmth and moisture. Eco-friendly pest control companies in the Alamo City employ fire ant broadcasting with spinosad-based baits, UV light traps, and organic barrier treatments that protect homes and the historic River Walk district's delicate ecosystem.`,
  charlotte: `Charlotte's Piedmont location brings a mix of termites, mosquitoes, carpenter bees, and brown recluse spiders that become especially active during the long Southern summers. Green pest control providers in the Charlotte metro use targeted bait stations, botanical perimeter sprays, and moisture-reduction strategies that address the root causes of infestations sustainably.`,
  raleigh: `Raleigh's position in the Research Triangle brings both suburban pest challenges and wooded-lot wildlife conflicts, from termites and fire ants to occasional copperhead encounters. Eco-friendly pest control companies in the Triangle area focus on habitat modification, pheromone-based monitoring traps, and low-impact treatments that align with the region's environmentally conscious culture.`,
  nashville: `Nashville's warm, wet springs and mild winters create breeding grounds for mosquitoes, brown recluse spiders, and Eastern subterranean termites throughout Middle Tennessee. Green pest control providers in Music City use essential oil barriers, targeted heat treatments, and biological pest controls that keep homes protected without the heavy chemical footprint of conventional methods.`,
  austin: `Austin's explosive growth has pushed neighborhoods into habitats shared with fire ants, scorpions, and Formosan termites that thrive in Central Texas limestone terrain. Eco-friendly pest control companies in the Austin area align with the city's green ethos, offering cedar oil treatments, beneficial insect releases, and integrated pest management programs that protect both homes and Barton Springs' watershed.`,
  jacksonville: `Jacksonville's coastal humidity and sprawling footprint make it a hotspot for mosquitoes, termites, and rodents that invade homes from the surrounding maritime forests and marshlands. Green pest control providers in Northeast Florida use tidal-zone-safe mosquito treatments, orange oil termite solutions, and exclusion-first rodent strategies that protect the St. Johns River ecosystem.`,
  "new-orleans": `New Orleans faces some of the most intense pest pressure in the nation — Formosan termites, mosquitoes, cockroaches, and rodents thrive in the city's subtropical humidity and aging building stock. Eco-friendly pest control companies in the Crescent City use sentricon termite systems, BTI larvicides, and botanical sprays that combat persistent infestations while safeguarding the unique wetland environment surrounding the city.`,
  "san-diego": `San Diego's mild Mediterranean climate keeps pest activity moderate but persistent, with Argentine ants, black widows, and drywood termites topping the list of common invaders. Green pest control providers in San Diego County use localized fumigation alternatives, botanical barrier sprays, and ant colony exclusion techniques that protect homes while respecting the region's coastal and canyon ecosystems.`,
  denver: `Denver's semi-arid climate brings seasonal waves of boxelder bugs, miller moths, and field mice seeking shelter from the mountain cold, along with occasional wasp and spider problems. Eco-friendly pest control companies along the Front Range use exclusion sealing, peppermint oil deterrents, and targeted trapping that handles Colorado's unique pest mix without relying on broad-spectrum chemical treatments.`,
  seattle: `Seattle's damp Pacific Northwest climate creates ideal conditions for carpenter ants, moisture-loving rodents, and silverfish that damage homes from the inside out. Green pest control providers in the Puget Sound region specialize in moisture management, bait station networks, and botanical treatments that address the root causes of infestations without harming Seattle's lush urban forests and salmon-bearing waterways.`,
  portland: `Portland's wet winters and mild summers fuel persistent problems with carpenter ants, rats, slugs, and moisture-dependent pests that exploit the city's older housing stock. Eco-friendly pest control companies in the Rose City use snap-trap rodent programs, boric acid treatments, and habitat modification techniques that reflect Portland's strong environmental values and protect the Willamette River watershed.`,
  chicago: `Chicago's extreme temperature swings drive seasonal pest invasions — mice and rats in winter, mosquitoes and wasps in summer, and cockroaches and bed bugs year-round in the city's dense housing. Green pest control providers across Chicagoland use IPM-first approaches, gel bait roach treatments, and exclusion-based rodent control that address pest problems effectively in both single-family homes and multi-unit buildings.`,
  "los-angeles": `Los Angeles contends with Argentine ants, black widows, drywood termites, and roof rats that thrive across the basin's diverse microclimates. Eco-friendly pest control companies throughout LA County use heat treatments for termites, essential oil perimeter barriers, and exclusion-first rodent management that protect homes from the Westside to the San Gabriel Valley without adding chemicals to the region's stressed watershed system.`,

  // ── California ──────────────────────────────────────────────────────────
  "san-francisco": `San Francisco's foggy, cool climate and dense Victorian housing stock create persistent problems with rats, carpenter ants, and silverfish that exploit aging foundations and crawl spaces. Eco-friendly pest control companies in the Bay Area use snap-trap rodent programs, boric acid dust treatments, and moisture barriers that protect homes from Pacific Heights to the Sunset without contaminating the city's coastal watershed.`,
  sacramento: `Sacramento's hot Central Valley summers and mild winters sustain year-round activity from Argentine ants, black widows, and subterranean termites that target the region's older neighborhoods. Green pest control providers in the Sacramento metro use heat-based termite treatments, botanical perimeter barriers, and IPM monitoring programs that keep homes pest-free without introducing chemicals into the American River watershed.`,
  "san-jose": `San Jose's warm Silicon Valley climate attracts Argentine ants, roof rats, and drywood termites that infiltrate both suburban homes and commercial properties. Eco-friendly pest control companies in the South Bay use localized fumigation alternatives, essential oil barriers, and exclusion sealing techniques that address pest entry points without broad-spectrum chemical applications near the region's sensitive creek ecosystems.`,
  fresno: `Fresno's intense Central Valley heat drives scorpions, black widows, and aggressive ant colonies into residential neighborhoods seeking shade and moisture. Green pest control providers in the Fresno area use diatomaceous earth, botanical sprays, and habitat modification strategies that manage pest populations effectively without adding chemical runoff to the San Joaquin Valley's agricultural irrigation systems.`,

  // ── Texas ───────────────────────────────────────────────────────────────
  "fort-worth": `Fort Worth's hot summers and clay-heavy soils create ideal conditions for termites, fire ants, and brown recluse spiders across Tarrant County's rapidly expanding neighborhoods. Eco-friendly pest control companies in Fort Worth use borate-based termite barriers, spinosad fire ant baits, and exclusion sealing that protect homes and families without relying on broad-spectrum chemicals in the Trinity River corridor.`,
  "el-paso": `El Paso's arid Chihuahuan Desert climate harbors bark scorpions, black widows, and roof rats that seek water and shelter inside residential properties. Green pest control providers in the Sun City use perimeter exclusion, diatomaceous earth applications, and UV light trapping that address desert pest pressures without introducing harsh chemicals into the fragile Rio Grande ecosystem.`,
  "corpus-christi": `Corpus Christi's coastal humidity and Gulf breezes drive persistent problems with mosquitoes, fire ants, and subterranean termites that threaten homes near the Coastal Bend shoreline. Eco-friendly pest control companies in Corpus Christi use BTI larvicides, botanical barrier sprays, and bait-based termite monitoring that protect properties without contaminating the bay's sensitive estuarine habitat.`,
  lubbock: `Lubbock's West Texas wind and semi-arid climate bring seasonal invasions of brown recluse spiders, scorpions, and field crickets that seek shelter in homes across the South Plains. Green pest control providers in the Hub City use exclusion sealing, sticky trap monitoring, and essential oil-based repellents that handle Lubbock's pest mix without heavy chemical treatments on the High Plains landscape.`,
  mcallen: `McAllen's subtropical Rio Grande Valley climate sustains year-round mosquito, fire ant, and cockroach pressure intensified by warm winters and abundant vegetation. Eco-friendly pest control companies in the McAllen metro use targeted larvicide programs, organic fire ant baits, and botanical perimeter treatments that protect Valley homes without chemical runoff into the region's vital irrigation canal system.`,

  // ── Florida ─────────────────────────────────────────────────────────────
  "st-petersburg": `St. Petersburg's waterfront humidity and warm Gulf temperatures fuel persistent problems with subterranean termites, mosquitoes, and palmetto bugs across the Pinellas peninsula. Green pest control providers in St. Pete use borate wood treatments, BTI mosquito dunks, and exclusion-based methods that protect homes and condos without introducing chemicals into Tampa Bay's fragile marine environment.`,
  "fort-lauderdale": `Fort Lauderdale's tropical climate and canal-laced neighborhoods create year-round breeding grounds for mosquitoes, German cockroaches, and drywood termites that damage waterfront properties. Eco-friendly pest control companies in the Greater Fort Lauderdale area use no-tent termite treatments, botanical barrier sprays, and larvicide programs that keep pests in check without compromising the Intracoastal Waterway ecosystem.`,
  "west-palm-beach": `West Palm Beach's warm, humid conditions attract subterranean termites, whiteflies, and fire ants that thrive in the lush tropical landscaping common throughout Palm Beach County. Green pest control providers in West Palm use orange oil termite treatments, beneficial nematode applications, and organic lawn pest programs that protect properties without chemical drift into the Lake Worth Lagoon system.`,
  tallahassee: `Tallahassee's canopy roads and humid North Florida climate create ideal conditions for carpenter ants, mosquitoes, and Eastern subterranean termites in the state capital's older neighborhoods. Eco-friendly pest control companies in Tallahassee use moisture management, bait-based termite monitoring, and botanical perimeter treatments that protect homes surrounded by live oaks without harming the region's spring-fed waterways.`,
  naples: `Naples' warm Gulf Coast climate and lush tropical landscaping attract drywood termites, whiteflies, and no-see-ums that challenge homeowners across Collier County. Green pest control providers in the Naples area use tent-free termite solutions, organic mosquito misting, and botanical sprays that protect properties from Marco Island to Bonita Springs without contaminating the Everglades watershed nearby.`,

  // ── New York ────────────────────────────────────────────────────────────
  "new-york": `New York City's dense urban environment creates intense pest pressure from cockroaches, bed bugs, and rats that thrive in the city's aging infrastructure and interconnected buildings. Eco-friendly pest control companies in Manhattan and across the five boroughs use gel bait treatments, heat remediation for bed bugs, and exclusion-based rodent strategies that address infestations without broadcast chemical spraying in tightly shared living spaces.`,
  brooklyn: `Brooklyn's mix of brownstones, pre-war apartments, and new construction brings persistent challenges from bed bugs, German cockroaches, and Norway rats exploiting the borough's layered building stock. Green pest control providers across Brooklyn use targeted gel baits, mattress encasements, and snap-trap rodent programs that eliminate pests effectively without exposing families in adjacent units to airborne chemical treatments.`,
  queens: `Queens' diverse neighborhoods and dense housing create year-round battles with cockroaches, bed bugs, and mice that move freely between connected row houses and apartment complexes. Eco-friendly pest control companies in Queens use IPM-first approaches, caulk-and-seal exclusion methods, and dust-based treatments in wall voids that address pest highways between units without relying on broad-spectrum sprays in this densely populated borough.`,

  // ── Pennsylvania ────────────────────────────────────────────────────────
  philadelphia: `Philadelphia's historic rowhomes and humid summers create persistent problems with termites, cockroaches, and mice that exploit shared walls and aging foundations across the city's dense neighborhoods. Green pest control providers in the Philadelphia metro use monitoring-based termite programs, gel bait roach treatments, and exclusion sealing that protect homes from Center City to the suburbs without heavy chemical applications near the Delaware and Schuylkill watersheds.`,
  pittsburgh: `Pittsburgh's river-valley humidity and older housing stock attract carpenter ants, stink bugs, and mice that invade homes across the city's hillside neighborhoods. Eco-friendly pest control companies in the Steel City use pheromone-based stink bug traps, boric acid treatments, and exclusion-first rodent strategies that address Pittsburgh's pest challenges without contaminating the Three Rivers confluence.`,

  // ── Ohio ────────────────────────────────────────────────────────────────
  columbus: `Columbus' humid continental climate drives seasonal waves of stink bugs, carpenter ants, and mice, with termites remaining active through the city's warm summers. Green pest control providers in the Columbus metro use pheromone traps, bait station monitoring, and exclusion sealing that handle Central Ohio's pest cycles effectively without over-reliance on chemical treatments near the Scioto River watershed.`,
  cleveland: `Cleveland's Lake Erie humidity and harsh winters push mice, cockroaches, and carpenter ants into homes across the city's older neighborhoods and inner-ring suburbs. Eco-friendly pest control companies in Greater Cleveland use exclusion-based rodent control, gel bait treatments, and moisture management strategies that address pest entry points without adding chemical runoff to the Lake Erie tributaries.`,
  cincinnati: `Cincinnati's Ohio River valley humidity creates ideal conditions for termites, mosquitoes, and brown recluse spiders that challenge homeowners across the Queen City's hilly terrain. Green pest control providers in the Cincinnati metro use bait-based termite monitoring, BTI larvicide treatments, and botanical barrier sprays that protect homes from Over-the-Rhine to the eastern suburbs without contaminating the Ohio River watershed.`,

  // ── Michigan ────────────────────────────────────────────────────────────
  detroit: `Detroit's cold winters drive mice and cockroaches indoors, while warm summers bring carpenter ants, mosquitoes, and wasps to the Motor City's older residential neighborhoods. Eco-friendly pest control companies in Metro Detroit use exclusion sealing, gel bait treatments, and BTI mosquito programs that address seasonal pest cycles without broad-spectrum chemical applications near the Detroit River and Great Lakes system.`,
  "grand-rapids": `Grand Rapids' West Michigan climate brings seasonal carpenter ant infestations, boxelder bug invasions, and persistent rodent problems as Lake Michigan's moisture fuels pest activity. Green pest control providers in the Grand Rapids area use botanical perimeter sprays, snap-trap rodent programs, and exclusion techniques that protect homes without chemical runoff into the Grand River and its Lake Michigan tributaries.`,

  // ── Minnesota ───────────────────────────────────────────────────────────
  minneapolis: `Minneapolis' frigid winters drive mice, boxelder bugs, and cluster flies indoors, while hot summers bring aggressive mosquito and wasp populations to the City of Lakes. Eco-friendly pest control companies in Minneapolis use exclusion sealing, essential oil deterrents, and BTI-based mosquito programs that protect families and the city's beloved chain of lakes without harsh chemical treatments.`,
  "st-paul": `St. Paul's older housing stock and tree-lined neighborhoods create persistent challenges from carpenter ants, mice, and seasonal invasions of Asian lady beetles seeking winter shelter. Green pest control providers in the Capital City use targeted bait stations, boric acid dust treatments, and habitat modification that address pest problems at their source without contaminating the Mississippi River corridor that runs through the heart of the city.`,

  // ── Indiana ─────────────────────────────────────────────────────────────
  indianapolis: `Indianapolis' humid Midwestern summers and cold winters create a seasonal pest cycle of mosquitoes, carpenter ants, and termites in warm months, with mice and brown recluse spiders invading homes as temperatures drop. Eco-friendly pest control companies across the Indianapolis metro use bait station monitoring, botanical barriers, and exclusion techniques that protect homes in the Circle City without heavy chemical treatments near White River and Eagle Creek.`,

  // ── Wisconsin ───────────────────────────────────────────────────────────
  milwaukee: `Milwaukee's Lake Michigan proximity and frigid winters drive mice, boxelder bugs, and Asian lady beetles indoors, while warm summers bring carpenter ants and mosquitoes to the Cream City's older neighborhoods. Green pest control providers in the Milwaukee area use exclusion sealing, pheromone traps, and BTI larvicide programs that handle seasonal pest waves without introducing chemicals into Milwaukee's lakefront and river ecosystems.`,

  // ── Missouri ────────────────────────────────────────────────────────────
  "kansas-city": `Kansas City's position at the confluence of two rivers brings humidity-driven pest pressure from termites, mosquitoes, and brown recluse spiders across both the Missouri and Kansas sides of the metro. Eco-friendly pest control companies in KC use bait-based termite monitoring, BTI larvicides, and botanical perimeter treatments that address the region's persistent pest challenges without adding chemicals to the Missouri River watershed.`,
  "st-louis": `St. Louis' Mississippi River humidity and aging brick housing stock create ideal conditions for termites, brown recluse spiders, and cockroaches that exploit the city's characteristic masonry walls. Green pest control providers across the Gateway City use heat treatments, monitoring-based termite programs, and exclusion sealing that protect homes in both the city and county without chemical contamination of the Mississippi floodplain ecosystem.`,

  // ── Kentucky ────────────────────────────────────────────────────────────
  louisville: `Louisville's Ohio River humidity and warm summers sustain year-round termite activity, brown recluse spider populations, and seasonal mosquito swarms across Derby City's diverse neighborhoods. Eco-friendly pest control companies in the Louisville metro use bait-based termite monitoring, essential oil perimeter barriers, and BTI larvicide programs that protect homes without chemical runoff into the Ohio River and Beargrass Creek systems.`,
  lexington: `Lexington's Bluegrass region humidity creates persistent problems with termites, carpenter ants, and brown recluse spiders in the Horse Capital's mix of historic and suburban homes. Green pest control providers in the Lexington area use monitoring-focused termite management, botanical sprays, and moisture control techniques that protect properties without introducing chemicals into the region's limestone karst aquifer system.`,

  // ── Tennessee ───────────────────────────────────────────────────────────
  memphis: `Memphis' Mississippi River humidity and warm Southern climate create intense pressure from termites, mosquitoes, and cockroaches that thrive in the Bluff City's older neighborhoods. Eco-friendly pest control companies in Memphis use sentricon termite systems, BTI larvicide programs, and gel bait treatments that combat persistent pest populations without adding chemical burden to the Mississippi River and Wolf River watershed.`,
  knoxville: `Knoxville's position in the Tennessee Valley brings humid summers that fuel mosquito, termite, and carpenter ant activity in the Marble City's wooded residential areas. Green pest control providers in the Knoxville metro use bait station monitoring, botanical perimeter treatments, and moisture management that address pest problems sustainably without contaminating the Tennessee River and Great Smoky Mountains watershed.`,
  chattanooga: `Chattanooga's river valley humidity and mild winters sustain year-round termite pressure, mosquito breeding, and brown recluse spider activity across the Scenic City's hillside neighborhoods. Eco-friendly pest control companies in Chattanooga use heat treatments, BTI larvicides, and exclusion-based methods that protect homes along Lookout Mountain and the Tennessee River corridor without harsh chemical applications.`,

  // ── Alabama ─────────────────────────────────────────────────────────────
  birmingham: `Birmingham's hot, humid climate and red clay soils create ideal conditions for subterranean termites, fire ants, and mosquitoes that challenge homeowners across the Magic City's sprawling metro. Green pest control providers in Birmingham use bait-based termite monitoring, spinosad fire ant treatments, and BTI larvicide programs that address persistent pest pressure without chemical contamination of the Cahaba River, one of the most biodiverse waterways in North America.`,
  huntsville: `Huntsville's Tennessee Valley location brings warm, humid summers that fuel mosquito, termite, and carpenter ant populations across the Rocket City's rapidly growing neighborhoods. Eco-friendly pest control companies in Huntsville use moisture management, botanical barrier sprays, and monitoring-based termite programs that protect homes without introducing chemicals into the Paint Rock River and Wheeler Lake ecosystems.`,

  // ── Virginia ────────────────────────────────────────────────────────────
  richmond: `Richmond's humid mid-Atlantic climate sustains year-round termite activity, mosquito breeding along the James River, and seasonal stink bug invasions that overwhelm the capital city's historic homes. Green pest control providers in the Richmond metro use bait-based termite monitoring, pheromone stink bug traps, and BTI larvicide programs that protect properties without contaminating the James River watershed.`,
  "virginia-beach": `Virginia Beach's coastal humidity and warm summers create persistent problems with mosquitoes, termites, and fire ants across the resort city's oceanfront and inland neighborhoods. Eco-friendly pest control companies in Virginia Beach use BTI mosquito treatments, borate-based termite barriers, and organic fire ant controls that protect homes and families without chemical runoff into the Chesapeake Bay and Back Bay ecosystems.`,

  // ── Maryland ────────────────────────────────────────────────────────────
  baltimore: `Baltimore's Chesapeake Bay humidity drives persistent termite, mosquito, and rodent problems in the Charm City's dense rowhome neighborhoods and harbor-adjacent communities. Eco-friendly pest control companies in Baltimore use monitoring-based termite programs, BTI larvicides, and exclusion-first rodent strategies that address the city's pest challenges without contributing to water quality issues in the Chesapeake Bay watershed.`,

  // ── Massachusetts ───────────────────────────────────────────────────────
  boston: `Boston's historic housing stock and coastal New England climate create persistent challenges from carpenter ants, mice, and termites, with tick-borne Lyme disease adding urgency to outdoor pest management. Eco-friendly pest control companies in Greater Boston use tick tube programs, exclusion-based rodent control, and bait station termite monitoring that protect families in the city's older neighborhoods without chemical impact on Boston Harbor and the Charles River.`,
  worcester: `Worcester's Central Massachusetts location brings seasonal waves of carpenter ants, mice, and stink bugs, with cold winters driving rodents into the Heart of the Commonwealth's older triple-deckers and colonial homes. Green pest control providers in the Worcester area use exclusion sealing, snap-trap rodent programs, and botanical barrier treatments that address pest entry points without relying on broad-spectrum chemicals near the Blackstone River watershed.`,

  // ── Connecticut ─────────────────────────────────────────────────────────
  hartford: `Hartford's Connecticut River valley climate and older housing stock create persistent problems with carpenter ants, termites, and mice that exploit the Insurance Capital's aging foundations and wooded suburban lots. Eco-friendly pest control companies in the Greater Hartford area use monitoring-based termite programs, boric acid treatments, and exclusion sealing that protect homes without contaminating the Connecticut River and its tributaries.`,

  // ── New Jersey ──────────────────────────────────────────────────────────
  newark: `Newark's dense urban environment and aging building stock create concentrated pest pressure from cockroaches, bed bugs, and rats that move through the city's interconnected rowhouses and apartment buildings. Green pest control providers in the Newark metro use gel bait treatments, heat remediation for bed bugs, and exclusion-based rodent control that address infestations effectively without broadcast chemical spraying in the Brick City's tightly packed residential areas.`,

  // ── Washington DC ───────────────────────────────────────────────────────
  washington: `Washington's Potomac River humidity and mix of historic rowhomes and modern buildings create year-round problems with termites, cockroaches, and rats across the nation's capital. Eco-friendly pest control companies in the DC metro use bait-based termite monitoring, gel bait roach treatments, and exclusion-first rodent strategies that protect homes from Georgetown to Capitol Hill without chemical contamination of Rock Creek Park and the Anacostia River watershed.`,

  // ── Nevada ──────────────────────────────────────────────────────────────
  reno: `Reno's high desert climate and proximity to the Sierra Nevada bring seasonal invasions of field mice, black widows, and boxelder bugs, with scorpions occasionally appearing in the Biggest Little City's newer subdivisions. Green pest control providers in the Reno-Sparks area use exclusion sealing, diatomaceous earth, and peppermint oil deterrents that manage pest populations without harsh chemical treatments in the Truckee River corridor.`,

  // ── Arizona ─────────────────────────────────────────────────────────────
  tucson: `Tucson's Sonoran Desert location harbors bark scorpions, black widows, and pack rats that seek shelter and water inside residential properties across the Old Pueblo. Eco-friendly pest control companies in Tucson use perimeter exclusion, diatomaceous earth applications, and UV light trapping that address desert pest pressures without introducing harsh chemicals into the Santa Cruz River basin and surrounding desert habitat.`,
  mesa: `Mesa's East Valley heat and rapid suburban growth push scorpions, roof rats, and termites into neighborhoods built on former desert and agricultural land. Green pest control providers in Mesa use exclusion sealing, targeted baiting systems, and habitat modification that protect homes without chemical overspray in the Salt River Project's canal system and surrounding Sonoran Desert environment.`,
  scottsdale: `Scottsdale's desert landscape and luxury residential properties face persistent challenges from bark scorpions, roof rats, and subterranean termites driven by irrigated landscaping amid arid surroundings. Eco-friendly pest control companies in Scottsdale use UV blacklight detection, exclusion-based scorpion management, and targeted bait stations that protect high-value homes without introducing chemicals into the McDowell Sonoran Preserve and Indian Bend Wash greenbelt.`,

  // ── New Mexico ──────────────────────────────────────────────────────────
  albuquerque: `Albuquerque's high desert climate brings seasonal invasions of scorpions, black widows, and field mice, with wind-driven tumbleweeds harboring pests against home foundations along the Rio Grande corridor. Green pest control providers in the Duke City use exclusion sealing, diatomaceous earth, and essential oil-based repellents that address the region's pest mix without chemical contamination of the Rio Grande bosque and its fragile cottonwood ecosystem.`,

  // ── Utah ────────────────────────────────────────────────────────────────
  "salt-lake-city": `Salt Lake City's four-season climate drives boxelder bugs and voles in from the surrounding foothills, while seasonal wasp activity and occasional black widow encounters keep homeowners vigilant. Eco-friendly pest control companies along the Wasatch Front use exclusion sealing, peppermint oil deterrents, and snap-trap rodent programs that handle the valley's pest mix without broad-spectrum chemical treatments near the Jordan River and Great Salt Lake watershed.`,

  // ── Idaho ───────────────────────────────────────────────────────────────
  boise: `Boise's Treasure Valley climate brings seasonal waves of boxelder bugs, hobo spiders, and field mice that seek shelter as temperatures swing between hot summers and cold winters. Green pest control providers in the Boise metro use exclusion sealing, botanical perimeter sprays, and targeted trapping that address Idaho's pest challenges without chemical runoff into the Boise River and its tributary network.`,

  // ── Oklahoma ────────────────────────────────────────────────────────────
  "oklahoma-city": `Oklahoma City's variable climate produces persistent challenges from brown recluse spiders, termites, and seasonal mosquito swarms fueled by spring storms and summer heat across the metro. Eco-friendly pest control companies in OKC use monitoring-based termite programs, botanical barrier treatments, and BTI larvicides that handle the city's pest pressure without adding chemicals to the Oklahoma and North Canadian River systems.`,
  tulsa: `Tulsa's Green Country humidity and warm summers create ideal conditions for termites, brown recluse spiders, and fire ants that challenge homeowners from midtown to the suburbs. Green pest control providers in the Tulsa metro use bait-based termite monitoring, essential oil barriers, and spinosad-based fire ant treatments that protect homes without contaminating the Arkansas River corridor and Keystone Lake watershed.`,

  // ── South Carolina ──────────────────────────────────────────────────────
  charleston: `Charleston's Lowcountry humidity and historic architecture create year-round pressure from subterranean termites, mosquitoes, and palmetto bugs in the Holy City's aging homes and waterfront properties. Eco-friendly pest control companies in the Charleston metro use moisture management, orange oil termite treatments, and BTI larvicide programs that protect the city's irreplaceable historic structures without contaminating the harbor and surrounding marsh ecosystems.`,
  columbia: `Columbia's position in the South Carolina Midlands brings intense summer heat that drives fire ants, termites, and mosquitoes into residential neighborhoods across the state capital. Green pest control providers in the Columbia area use spinosad-based fire ant baits, bait station termite monitoring, and botanical perimeter sprays that address persistent pest pressure without chemical runoff into the Congaree River and its nationally protected floodplain forest.`,

  // ── Georgia ─────────────────────────────────────────────────────────────
  savannah: `Savannah's coastal humidity and historic squares create a lush environment where mosquitoes, termites, and fire ants thrive year-round in the Hostess City's Spanish moss-draped neighborhoods. Eco-friendly pest control companies in Savannah use BTI larvicide programs, orange oil termite treatments, and organic fire ant controls that protect the city's irreplaceable historic homes without contaminating the Savannah River estuary and surrounding marshlands.`,
  augusta: `Augusta's warm, humid climate along the Savannah River sustains persistent termite, fire ant, and mosquito populations that challenge homeowners across the Garden City's established neighborhoods. Green pest control providers in the Augusta metro use bait-based termite monitoring, botanical barrier sprays, and BTI mosquito treatments that address year-round pest pressure without chemical contamination of the Savannah River and Augusta Canal ecosystems.`,
};

// Fallback copy for cities not explicitly listed
const CITY_INTRO_FALLBACK = (cityName: string) =>
  `Discover eco-friendly pest control companies in ${cityName}. Our curated directory features providers who use green, low-toxicity methods — including integrated pest management, botanical treatments, and exclusion techniques — to protect your home and family from common pests without harsh chemicals. Find a trusted eco-friendly exterminator near you today.`;

export function getCityIntroCopy(city: string): string {
  const cityName = city
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");

  return CITY_INTRO_COPY[city] || CITY_INTRO_FALLBACK(cityName);
}

// ─────────────────────────────────────────────────────────────────────────────
// STATE INTRO COPY
// ─────────────────────────────────────────────────────────────────────────────

const STATE_INTRO_COPY: Record<string, string> = {
  texas: `Texas faces an intense year-round pest landscape driven by heat, humidity, and vast geography — from Formosan termites devastating Gulf Coast homes to fire ants blanketing suburban lawns and scorpions in the Hill Country. Eco-friendly pest control companies across the Lone Star State use targeted baiting, heat treatments, and biological controls that handle Texas-sized pest problems without broad-spectrum chemicals.`,
  florida: `Florida's subtropical climate makes it one of the most pest-challenged states in the nation, with subterranean termites, mosquitoes, palmetto bugs, and invasive species like the Asian citrus psyllid creating constant pressure. Green pest control providers throughout the Sunshine State specialize in moisture management, tent-free termite alternatives, and larvicide programs that protect homes and Florida's fragile aquifer system.`,
  california: `California's diverse climate zones — from coastal fog to desert heat — create pest challenges ranging from drywood termites and Argentine ants in Southern California to gophers and yellow jackets in the north. Eco-friendly pest control companies statewide leverage the state's progressive pesticide regulations and offer IPM-first approaches, heat fumigation, and botanical treatments that meet California's strict environmental standards.`,
  georgia: `Georgia's hot, humid summers and mild winters sustain year-round pressure from mosquitoes, termites, fire ants, and brown recluse spiders across the Peach State. Green pest control providers from Atlanta to Savannah use botanical perimeter treatments, beneficial nematodes for fire ant control, and moisture management strategies that protect homes without contaminating Georgia's rivers and coastal marshlands.`,
  arizona: `Arizona's desert environment harbors bark scorpions, black widows, Africanized bees, and subterranean termites that cause significant damage across the Sun Belt. Eco-friendly pest control companies throughout Arizona use perimeter exclusion, diatomaceous earth, and targeted UV trapping that address the state's unique pest mix while preserving the fragile Sonoran Desert ecosystem.`,
  "north-carolina": `North Carolina's varied terrain — from the Blue Ridge Mountains to the Outer Banks — produces diverse pest challenges including termites, mosquitoes, fire ants, and carpenter bees. Green pest control providers across the Tar Heel State use regionally adapted IPM programs, bait-based termite management, and botanical sprays that protect homes from the Piedmont to the coast.`,
  tennessee: `Tennessee's warm, humid climate fosters persistent problems with termites, mosquitoes, brown recluse spiders, and carpenter ants from Memphis to Knoxville. Eco-friendly pest control companies across the Volunteer State employ essential oil barriers, heat treatments, and exclusion-based methods that handle the state's pest challenges without harsh chemical applications in homes and schools.`,
  colorado: `Colorado's semi-arid climate and dramatic elevation changes create a unique pest landscape — miller moths and boxelder bugs at lower elevations, mice seeking winter shelter, and occasional yellow jacket nests in mountain communities. Green pest control providers along the Front Range and beyond use exclusion sealing, peppermint-based deterrents, and targeted trapping suited to Colorado's environmentally conscious residents.`,
  washington: `Washington State's wet western climate and dry eastern plateau create distinct pest zones — carpenter ants and moisture-loving rodents west of the Cascades, and spiders and occasional wasp infestations in the drier east. Eco-friendly pest control companies throughout the Evergreen State prioritize moisture management, botanical treatments, and habitat modification that protect both homes and salmon-bearing waterways.`,
  oregon: `Oregon's Pacific Northwest dampness fuels year-round activity from carpenter ants, rats, silverfish, and moisture-dependent wood-destroying organisms. Green pest control providers across the Beaver State use snap-trap rodent programs, boric acid treatments, and exclusion techniques that reflect Oregon's environmental leadership and protect the state's rivers, forests, and urban tree canopy.`,
  "new-york": `New York's dense urban areas and rural regions face very different pest challenges — bed bugs and cockroaches in the city, termites and carpenter ants upstate, and rodents everywhere in between. Eco-friendly pest control companies across the Empire State use gel baits, heat treatments, and IPM strategies that address infestations effectively in everything from high-rise apartments to colonial-era homes.`,
  illinois: `Illinois experiences intense seasonal pest cycles — rodent invasions in harsh winters, mosquito swarms in humid summers, and termite pressure year-round in the state's clay-heavy soils. Green pest control providers from Chicago to Springfield use exclusion-based rodent control, BTI mosquito treatments, and bait station termite monitoring that protect homes across the Prairie State sustainably.`,
  ohio: `Ohio's four-season climate brings seasonal invasions of stink bugs, ladybugs, and mice in fall and winter, plus mosquitoes, yellow jackets, and carpenter ants in the warmer months. Eco-friendly pest control companies across the Buckeye State use IPM-first approaches, botanical barrier sprays, and exclusion techniques that handle Ohio's diverse pest mix without over-relying on chemical treatments.`,
  pennsylvania: `Pennsylvania homeowners face termites in the southeast, stink bug invasions statewide, and rodent pressure in both urban Philadelphia and rural areas. Green pest control providers across the Keystone State use pheromone traps for stink bugs, bait-based termite monitoring, and exclusion-first rodent strategies that address the state's varied pest challenges with minimal environmental impact.`,
  virginia: `Virginia's mid-Atlantic location brings a full spectrum of pest challenges — from termites and mosquitoes in the Tidewater region to carpenter ants and brown recluse spiders in the western mountains. Eco-friendly pest control companies across the Commonwealth use regionally targeted IPM programs, botanical treatments, and moisture management that protect homes from Richmond to Roanoke.`,
  maryland: `Maryland's humid Chesapeake Bay climate fuels persistent mosquito, termite, and rodent problems, with stink bugs adding seasonal misery across the state. Green pest control providers throughout the Old Line State prioritize Chesapeake Bay-safe treatments, using botanical sprays, exclusion methods, and biological controls that reduce pest populations without contributing to the bay's water quality challenges.`,
  massachusetts: `Massachusetts faces seasonal pest waves — carpenter ants and termites in spring, mosquitoes and ticks carrying Lyme disease in summer, and mice seeking warmth in historic homes come fall. Eco-friendly pest control companies across the Bay State use tick tubes, targeted bait stations, and exclusion techniques that protect both families and the region's sensitive coastal and woodland ecosystems.`,
  "new-jersey": `New Jersey's dense population and varied geography create concentrated pest pressure — from termites in the Pine Barrens to mosquitoes in the shore communities and rodents throughout the urban corridor. Green pest control providers across the Garden State use monitoring-based termite programs, larvicide treatments, and IPM strategies tailored to New Jersey's mix of suburban, urban, and coastal environments.`,
  michigan: `Michigan's Great Lakes climate brings seasonal carpenter ant infestations, boxelder bug invasions, and persistent rodent problems as temperatures swing between humid summers and bitter winters. Eco-friendly pest control companies across the Wolverine State use exclusion sealing, botanical perimeter treatments, and moisture management that address pest entry points without chemical overspray near Michigan's lakes and rivers.`,
  minnesota: `Minnesota's extreme winters drive mice, boxelder bugs, and cluster flies indoors, while warm summers bring mosquitoes, wasps, and carpenter ants. Green pest control providers across the North Star State use exclusion-first strategies, essential oil deterrents, and BTI-based mosquito programs that handle the state's seasonal pest cycles without harsh chemicals in the Land of 10,000 Lakes.`,
  indiana: `Indiana's agricultural landscape and humid summers create persistent problems with field mice, mosquitoes, termites, and brown recluse spiders across the Hoosier State. Eco-friendly pest control companies throughout Indiana use bait station monitoring, botanical barriers, and habitat modification techniques that protect homes and farms without broad-spectrum pesticide applications.`,
  missouri: `Missouri's central location brings both Southern and Northern pest challenges — termites and brown recluse spiders thrive in the warm, humid summers, while mice and cockroaches invade homes during cold winters. Green pest control providers across the Show-Me State use heat treatments, glue board monitoring, and targeted baiting that address Missouri's diverse pest mix sustainably.`,
  wisconsin: `Wisconsin's cold winters drive rodents, boxelder bugs, and Asian lady beetles indoors, while summers bring mosquitoes, wasps, and carpenter ants to the state's lake-heavy landscape. Eco-friendly pest control companies across the Badger State use exclusion techniques, pheromone-based trapping, and botanical treatments that protect homes without contaminating Wisconsin's cherished lakes and waterways.`,
  louisiana: `Louisiana faces some of the nation's most intense pest pressure — Formosan termites cause hundreds of millions in damage annually, while mosquitoes, cockroaches, and fire ants thrive in the state's subtropical humidity. Green pest control providers across the Pelican State use sentricon monitoring systems, BTI larvicides, and botanical treatments that combat relentless pest activity while protecting Louisiana's bayous and wetlands.`,
  "south-carolina": `South Carolina's Lowcountry humidity and coastal geography create ideal conditions for termites, mosquitoes, fire ants, and palmetto bugs that challenge homeowners from Charleston to Greenville. Eco-friendly pest control companies across the Palmetto State use moisture management, orange oil termite treatments, and biological mosquito controls that protect homes without harming the state's marshes and barrier island ecosystems.`,
  alabama: `Alabama's long, hot summers and mild winters sustain year-round termite, mosquito, and fire ant activity that puts the Yellowhammer State among the most pest-challenged in the Southeast. Green pest control providers throughout Alabama use baiting systems, larvicide programs, and botanical treatments that address persistent pest pressure without contributing to runoff in the state's rivers and Mobile Bay watershed.`,
  oklahoma: `Oklahoma's variable climate — from humid eastern forests to dry western plains — produces a pest mix including brown recluse spiders, termites, scorpions, and seasonal mosquito swarms. Eco-friendly pest control companies across the Sooner State use regionally adapted IPM programs, exclusion sealing, and low-toxicity treatments that handle Oklahoma's diverse pest challenges without unnecessary chemical exposure.`,
  kentucky: `Kentucky's warm, humid conditions foster termites, carpenter ants, brown recluse spiders, and seasonal mosquito populations throughout the Bluegrass State. Green pest control providers from Louisville to Lexington use bait-based termite monitoring, botanical perimeter sprays, and moisture management strategies that protect homes and Kentucky's limestone cave ecosystems from chemical contamination.`,
  connecticut: `Connecticut's older housing stock and wooded suburban lots create persistent challenges with termites, carpenter ants, ticks carrying Lyme disease, and mice that exploit gaps in aging foundations. Eco-friendly pest control companies across the Nutmeg State use tick tube programs, exclusion-based rodent control, and monitoring-focused termite management that protect families and the Long Island Sound watershed.`,
  nevada: `Nevada's desert climate drives scorpions, black widows, roof rats, and occasional bark beetle infestations, with pests seeking water and shelter in residential areas across the Silver State. Green pest control providers from Las Vegas to Reno use exclusion sealing, diatomaceous earth, and UV light trapping that manage desert pest populations without introducing harsh chemicals into Nevada's fragile arid environment.`,
};

// Fallback copy for states not explicitly listed
const STATE_INTRO_FALLBACK = (stateName: string) =>
  `Find eco-friendly pest control companies across ${stateName}. Our directory features providers committed to green, low-toxicity methods — including integrated pest management, botanical treatments, and humane exclusion techniques — that protect your home and family from local pests without relying on harsh chemicals. Browse trusted eco-friendly exterminators in ${stateName} today.`;

export function getStateIntroCopy(stateSlug: string): string {
  const stateName = stateSlug
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");

  return STATE_INTRO_COPY[stateSlug] || STATE_INTRO_FALLBACK(stateName);
}
